### ISSUE TITLE
function ParticleQ is broken

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#106]
@uukhas found that the function ``TreeMasses`ParticleQ`` does not what it's suppose to. For example in the `SM` `GetParticles[]` gives
```mathematica
{VG, gG, Hp, Fv, Ah, hh, VP, VZ, gP, gZ, gWp, gWpC, Fd, Fu, Fe, VWp}
```
but
```mathematica
ParticleQ /@ {VG, gG, Hp, Fv, Ah, hh, VP, VZ, gP, gZ, gWp, gWpC, Fd, 
  Fu, Fe, VWp} 
= {True, True, True, False, True, True, True, True, True, True, True, \
True, False, False, False, True}
```
There's also a problem with conjugation
```mathematica
ParticleQ /@ (AntiField /@ {VG, gG, Hp, Fv, Ah, hh, VP, VZ, gP, gZ, 
    gWp, gWpC, Fd, Fu, Fe, VWp}) 
= {True, False, False, False, True, True, True, True, True, True, \
False, False, False, False, False, False}
```
The silver lining is that this function was never used.  Should we fix it or remove this function altogether?

**Comment by Expander** [comment]
Many thanks for reporting!

As far as I can see, there is no equivalent function. For this reason, I'd propose to fix it (not remove it). I'll prepare a fix.

**Comment by wkotlarski** [comment]
```mathematica
IsSMParticle /@ (AntiField /@ GetParticles[])
```
returns
```mathematica
{True, False, False, False, True, True, True, True, True, True, \
False, False, False, False, False, False}
```
Is this what you want?

P.s. @uukhas, does this function do what you want now?
