### ISSUE TITLE
compilation of test_linalg2.cpp uses 4 GB of memory

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#110]
@Expander, is this fine?

**Comment by Expander** [comment]
It is certainly a problem. It is one of the reasons why the nightly tests sometimes crash the test machine.

@jhyeon is there a way to reduce the memory used during compilation?

**Comment by jhyeon** [comment]
Sorry for the troubles.  Let me rewrite it so that it compiles consuming less resources.
