### ISSUE TITLE
warnings from npointfunctions and cxxdiagram tests

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#113]
There are annoying warnings coming from building 
```
test/test_SM_npointfunctions.cpp
test/test_SM_cxxdiagrams.cpp
```
One is
```
Mass matrix for Hp does not exist!
Mass matrix for Fv does not exist!
Mass matrix for Ah does not exist!
Mass matrix for hh does not exist!
```
and the other one is
```
Transpose::nmtx: 
   The first two levels of the one-dimensional list {} cannot be transposed.
```
I'd like to fix it cause it annoys me. Can anyone confirm that you're seeing the same thing?

**Comment by Expander** [comment]
Yes, I'm seeing the same thing. Some of the messages may come from the request to calculate some observables of particles that don't exist.

**Comment by uukhas** [comment]
@wkotlarski, I have rewritten tests some weeks ago, as well as this transpose message. I will write the explanation soon.

**Comment by wkotlarski** [comment]
This is now partially solved. What I'd still like to know is

1. Where does this warning come from and can it be eliminated
```
Mass matrix for Glu does not exist!
Mass matrix for Fv does not exist!
Mass matrix for Glu does not exist!
Mass matrix for Fv does not exist!
```
2. Can we do something with this one
```
args::shdw: Symbol args appears in multiple contexts {FeynArts`, Global`}
    ; definitions in context FeynArts`
     may shadow or be shadowed by other definitions.
```

**Comment by uukhas** [comment]
@wkotlarski, 

1. Set of messages comes from every place where ```SARAH`MassMatrix``` (or, more precisely, ```SARAH`ShowMassMatrix[y,True]```) is called. 

Right after initialization I got messages, similar to yours because of  ```TreeMasses`ConvertSarahMassMatrices[]``` call, when one of the mentioned above functions is called.

2. It might come from `NPointFunctions` routines. It seems for me that inside your version of `Utils` one has created ```Global`args``` somewhere (most likely inside a call of a function) and because inside NPointFunctions/internal.m `Utils + FeynArts` are loaded it might lead to this message.

**Comment by uukhas** [comment]
@wkotlarski, 
The solution to "mass matrix" is found. One has to use ```FlexibleSUSY`Private`PrepareUnrotatedParticles```

**Comment by wkotlarski** [comment]
[So close...](https://github.com/FlexibleSUSY/FlexibleSUSY/files/3838584/vova.txt)

**Comment by uukhas** [comment]
Dear @wkotlarski, there is a problem with FormCalc on your PC. One should change the lines of **FormCalc.m**
```
$FormCalcDir = DirectoryName[ File /.
FileInformation[System`Private`FindFile[$Input]] ]
```
to 
```
$FormCalcDir ="/path/to/directory/of/FormCalc";
```
This is correlated with #125.
