### ISSUE TITLE
why do we need our own abs function

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#116]
Super small thing. In file `numerics.cpp` we define a function `dabs`. Why do we need it? Seems that in `c++14` `is_zero` function works equally well with `std::abs`. Am I missing something?

**Comment by Expander** [comment]
I've created this function in order to have a `constexpr` `abs` function, which thus is a "pure" function and can be optimized away by the compiler. To my knowledge `std::abs` is not constexpr, and so I don't know whether the compiler will recognize it as a "pure" function.

**Comment by wkotlarski** [comment]
I've also read that `std::abs` is not `constexpr`. That's why I'm surprised why am I allowed to use it inside of a `constexpr` function.

**Comment by Expander** [comment]
What you see could be valid, see
https://stackoverflow.com/questions/47726503/calling-non-constexpr-function-from-constexpr-allowed-in-some-conditions

However, I'd prefer to call the `constexpr` function in order to give the compiler more information to optimize the code.
