### ISSUE TITLE
make test shall return an exit code

### ISSUE THREAD

**Issue by Expander** [FlexibleSUSY/FlexibleSUSY#133]
For the CI tests the following behavior of `make test*` would be convenient:

* executing a single test via `make` should return an exit code indicating whether the test has failed or passed:
* executing all tests via `make` (targets: `all-test`, `execute-tests`, `execute-meta-tests`, `execute-shell-tests`, `execute-compiled-tests`) should return an exit code indicating whether one (or more) tests have failed or all tests passed

**Comment by Expander** [comment]
# Proposal 1
In the branch feature-test-exit-code2 I've implemented a first proposal to address the raised points:

* For each individual test `make` returns the exit code of the test. This is achieved by the function `write_test_result_file()` which returns the exit code of the test

This change leads to a changed behavior when running all tests via `make`: As soon as one test fails, `make` stops running the remaining tests. To force `make` to execute all tests, one shall call
~~~
make -k all-test
~~~
where `-k` (`--keep-going`) forces make to continue in case of errors and return a corresponding error code at the end. See https://www.gnu.org/software/make/manual/html_node/Errors.html#Errors . This is the desired behavior of the second point raised in the issue.

### Pros:
* `make` returns exit codes of the test(s)
### Cons:
* One must pass `-k` as argument to `make` when running all tests

**Comment by wkotlarski** [comment]
I think it's fine. Also, in case of test, all of them should pass. So even if it fails on first error, it's still fine.

**Comment by wkotlarski** [comment]
@Expander I'm not sure if it works as expected. There was no change in tests [output](https://github.com/FlexibleSUSY/FlexibleSUSY/runs/354794492).

**Comment by Expander** [comment]
Sorry, my fault. I did merge the wrong branch. I've now corrected the mistake.
