### ISSUE TITLE
Unit tests action fails on pull request

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#136]
Error message:
```
Run docker exec builder bash -c "git clone --single-branch --branch ${GITHUB_REF##*/} --depth=1 https://github.com/${GITHUB_REPOSITORY}.git FlexibleSUSY"
Cloning into 'FlexibleSUSY'...
warning: Could not find remote branch merge to clone.
fatal: Remote branch merge not found in upstream origin
```

**Comment by wkotlarski** [comment]
This should now be fixed. I'm waiting for a next pull request to check if it works as expected.

**Comment by Expander** [comment]
What was the issue?

**Comment by wkotlarski** [comment]
The problem was that I was assuming that the repo name is `FlexibleSUSY`. For pull request, this is not true. We now use predefined github action to handle cloning of the appropriate repo and then mount it under the docker image. it should work not only for pushes and pull requests and is also nice cause there is less hand written code.
