### ISSUE TITLE
scan-slha.sh fails on Ubuntu

### ISSUE THREAD

**Issue by uukhas** [FlexibleSUSY/FlexibleSUSY#139]
Instead of numbers in the output I get

    MINPAR[3]         MASS[25]          YU[2:2]
            -                -                -
            -                -                -
            -                -                -
            -                -                -
            -                -                -

@Squarkfinder also had this problem and he suggested the working solution, namely:

installation of **gawk** solved the problem.

Can the **scan-slha.sh** script be modified somehow to catch this problem automatically?

**Comment by Expander** [comment]
Many thanks for the bug report!

Do you know if the vanilla version of ubuntu has another version of `awk` installed? Or is `awk` not available in the vanilla ubuntu at all?

**Comment by uukhas** [comment]
@Expander, I have the default desktop Ubuntu 18. About vanilla version I do not know.

**Comment by Expander** [comment]
Have you `mawk` installed for example?

**Comment by uukhas** [comment]
Yes I have.

**Comment by Expander** [comment]
Thanks for the info, I'll prepare a fix.
