### ISSUE TITLE
"ar" is complaining 

### ISSUE THREAD

**Issue by uukhas** [FlexibleSUSY/FlexibleSUSY#141]
During evaluation of `make` command among standard `Building <something>` there are a lot of messages from `ar`:
   ```ar: `u' modifier ignored since `D' is the default (see `U')```.

In order to remove it one can change the default setup in `configure` file from 
   ```STATIC_LIB_CMD="ar cru"``` to ```STATIC_LIB_CMD="ar cruU"```.

**Comment by Expander** [comment]
Thanks for the hint!
fixed in a94f5bf64020e
