### ISSUE TITLE
FormCalc cannot get SystemID

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#142]
`FormCalc` installation in actions sometimes fails. I'm not sure why it happens. For now the solution is to restart tests manually.

**Comment by wkotlarski** [comment]
The immiadiate source of the error is the line
``` bash
`"$mathcmd" -run 'Print[7 673, $SystemID]; Exit[]' < /dev/null` =~ 4711([^$'\r\n']*)
```
from `FormCalc`'s `compile` script.

**Comment by Expander** [comment]
Interesting. Do you know what exactly is going wrong with this command?

**Comment by wkotlarski** [comment]
No sure. For now I've added a test if `wolframscript` and `math` commands are working the moment we set up wolfram engine on the image.

**Comment by wkotlarski** [comment]
I've reinstated tests with `LoopTools`. For now everything seems to work.
