### ISSUE TITLE
Unexpected behavior of DecreaseIndexLiterals

### ISSUE THREAD

**Issue by uukhas** [FlexibleSUSY/FlexibleSUSY#152]
``Parameters`DecreaseIndexLiterals`` has the following potential problem (it comes from ``Parameters`IncreaseIndexLiterals``):

```
DecreaseIndexLiterals[{f1@1, f1@f1@1, f2@f1@1}, {f1}]
```
leads to 
```
{f1[0], f1[f1[1]], f2[f1[0]]}
```
instead of
```
{f1[0], f1[f1[0]], f2[f1[0]]}
```

Also, the following call:
```
DecreaseIndexLiterals[{f1@1, f2@1, f1@f2@1, f2@f1@1}, {f1, f2}]
```
leads to
```
{f1[0], f2[0], f1[f2[1]], f2[f1[1]]}
```

So, the problem is that in ``head@head@integer`` expressions numbers are not always decreased, which potentially can be dangerous.

If we do not expect this form of a call, then the solution *could be* the replacement in
```
DecreaseIndexLiterals[expr_]
DecreaseIndexLiterals[expr_, heads_List]
```
of ``expr_`` to 
```
expr:Alternatives[
   _Symbol,
   _Symbol[__Integer],
   _Symbol[{__Integer}],
   {
      Alternatives[
         _Symbol, 
         _Symbol[__Integer],
         _Symbol[{__Integer}]
      ]..
   }
]
```
and ``heads_List`` to
```
heads:{__Symbol}
```
as well.

**Comment by Expander** [comment]
I think the behavior of `DecreaseIndexLiterals` should be such that
~~~
DecreaseIndexLiterals[{f1@1, f2@1, f1@f2@1, f2@f1@1}, {f1, f2}]
~~~
yields
~~~
{f1[0], f2[0], f1[f2[0]], f2[f1[0]]}
~~~
iff `f1` and `f2` are either

* input parameters (with an index) or
* extra parameters (with an index) or
* output parameters (with an index) or
* model parameters (with an index), like masses or mixing matrices.

I.e. indices should be decreased for all symbols that appear at the C++ level and that carry an index.

Reason: In SARAH indices range from `1, 2, ...`, while in C/C++ we need `0, 1, ...`.

**Comment by Expander** [comment]
Given this intention of `DecreaseIndexLiterals`, can you give a short example where this function yields incorrect behavior in such a context?

**Comment by wkotlarski** [comment]
@uukhas, is this still a problem or can we it?

**Comment by uukhas** [comment]
It looks like that this function is not used incorrectly so far. But still: it can be, because nothing forbids the user to do so.

**Comment by wkotlarski** [comment]
"With great power comes great responsibility". Will you want to patch it?

**Comment by uukhas** [comment]
It seems that since long ago I did not encounter any problem with this function.
