### ISSUE TITLE
passing tests report FAILED

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#156]
On my PC some tests which work fine (see [test_SM_matching_selfenergy_Fd.x.log](https://github.com/FlexibleSUSY/FlexibleSUSY/files/4356802/test_SM_matching_selfenergy_Fd.x.log)) generate the following error
```
/bin/sh: line 3: 28124 Stop               (core dump) BOOST_TEST_CATCH_SYSTEM_ERRORS="no" test/test_SM_matching_selfenergy_Fd.x --log_level=test_suite >> test/test_SM_matching_selfenergy_Fd.x.log 2>&1
```

**Comment by Expander** [comment]
Do you get this error only when using LoopTools?

Quite often this error is caused by writing beyond the end of a buffer/array. Can you please run this test with valgrind?
~~~
valgrind test/test_SM_matching_selfenergy_Fd.x
~~~

**Comment by wkotlarski** [comment]
Here's the [log](https://github.com/FlexibleSUSY/FlexibleSUSY/files/4356953/valgrind.log)

**Comment by Expander** [comment]
Hmm, that does not say much, unfortunately.
Would you mind compiling with debug symbols and run the test again (w/ and w/o valgrind)?
~~~
make clean
./configure --enable-debug [...]
make -j4
make test/test_SM_matching_selfenergy_Fd.x
~~~

**Comment by wkotlarski** [comment]
This doesn't change the output :(

**Comment by Expander** [comment]
Is the valgrind output the same, too? :/

**Comment by uukhas** [comment]
@wkotlarski, is the problem solved now?

**Comment by wkotlarski** [comment]
Yes!
