### ISSUE TITLE
Possiblly wrong loop function calculation

### ISSUE THREAD

**Issue by uukhas** [FlexibleSUSY/FlexibleSUSY#159]
During preparation of a unit test for loop library interface I randomly have chosen a point, which surprisingly gave different (wrong) number for `softsusy` library:

```
softsusy::b0(1., 1., std::sqrt(2.), std::sqrt(50.)) -> 4.78005
```
but for `COLLIER`, `Looptools` and  `Package-X` the output is `3.64808`.

**Comment by Expander** [comment]
Many thanks, I'll fix that!
