### ISSUE TITLE
make install-src creates inconsistent source tree

### ISSUE THREAD

**Issue by Expander** [FlexibleSUSY/FlexibleSUSY#171]
The source tree exported by the `make install-src` command is inconsistent:
~~~
./configure --with-models=SM --with-install-dir=install
make
make install-src

cd install

./configure
make
~~~
I get the following error messages when running `make` inside the `install` directory:
~~~
grep: models/SM/cxx_qft/vertices.mk: No such file or directory
Building src/build_info.o
[...]
Building models/SM/run_SM.x
Building models/SM/run_cmd_line_SM.x
Building models/SM/scan_SM.x
Building models/SM/SM_librarylink.so
/usr/bin/ld: /home/avoigt/research/FlexibleSUSY/install/models/SM/libSM.a(SM_a_muon.o): in function `(anonymous namespace)::calculate_a_muon_impl(flexiblesusy::SM_mass_eigenstates const&, softsusy::QedQcd const&)':
SM_a_muon.cpp:(.text+0x532): undefined reference to `flexiblesusy::SM_cxx_diagrams::detail::unit_charge(flexiblesusy::SM_cxx_diagrams::context_base const&)'
/usr/bin/ld: SM_a_muon.cpp:(.text+0x578): undefined reference to `flexiblesusy::SM_cxx_diagrams::detail::unit_charge(flexiblesusy::SM_cxx_diagrams::context_base const&)'
/usr/bin/ld: /home/avoigt/research/FlexibleSUSY/install/models/SM/libSM.a(SM_FFV_form_factors.o): in function `flexiblesusy::SM_FFV_form_factors::calculate_Fe_Fe_VP_form_factors(int, int, flexiblesusy::SM_mass_eigenstates const&, bool)':
SM_FFV_form_factors.cpp:(.text+0x127e): undefined reference to `flexiblesusy::SM_cxx_diagrams::detail::VertexImpl<flexiblesusy::SM_cxx_diagrams::fields::Ah, flexiblesusy::SM_cxx_diagrams::fields::bar<flexiblesusy::SM_cxx_diagrams::fields::Fe>, flexiblesusy::SM_cxx_diagrams::fields::Fe>::evaluate(std::array<int, 2ul> const&, flexiblesusy::SM_cxx_diagrams::context_base const&)'
~~~
It seems that source from the `cxx_diagrams` sub-module are missed from being installed.

Btw, the following should be a successful (approximately) infinite loop:
~~~
for i in `seq 10000`
do
   ./configure --with-models=SM --with-install-dir=install
   make
   make install-src
   cd install/
done
~~~

**Comment by wkotlarski** [comment]
I cannot even do `./configure` in install
```
grep: models/SM/FlexibleSUSY.m: No such file...
```

**Comment by uukhas** [comment]
I will look at this, but currently I absolutely have no idea what can go wrong, because I never used these options.

What does `install-src` do?

**Comment by Expander** [comment]
Hi @uukhas , sorry, I was not aware of that. I'll prepare a patch to the configure script and maybe you can have a look at it?

@wkotlarski : Would you mind looking at the concerning the `cxx_diagrams`?

**Comment by Expander** [comment]
@uukhas `make install-src` creates a directory (specified via `--with-install-dir=`) and copies the generated FS source code to that folder. In that folder one will find a working FS version, but without the meta code and the tests.

This is in particular useful if you want to create a standalone FS version with pre-generated models without requiring Mathematica, FeynArts, FormCalc. For example you may develop a fancy model (maybe including hand-written C++ source code etc.) and want to distribute it in an alone-standing FS package. `make install-src` will create this alone-standing distribution.

**Comment by uukhas** [comment]
@Expander, the problem comes from `install` command. In some places in the code there is something like:
```
install    /<5directories>/file             /<4directories>/
```
and this `file` is not copied! only  
```
install    /<5directories>/file             /<5directories>/
```
works appropriately.

I will make a PR for PR #172 in order to fix this somehow.
