### ISSUE TITLE
Weird vertex of SMSU3

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#181]
In `SMSU3` there's a following vertex
```
{{VCo2[{ct1, lt1}], Ff[{ct2, ct2}], 
  bar[Ff[{ct3, ct3}]]}, {1/
   2 I g4 PhaseFR conj[PhaseFR] Delta[ct2, ct3] Lam[ct1, ct3, ct2], 
  LorentzProduct[gamma[lt1], PL]}, {1/
   2 I g4 PhaseFL conj[PhaseFL] Delta[ct2, ct3] Lam[ct1, ct3, ct2], 
  LorentzProduct[gamma[lt1], PR]}}
```
There are fields with duplicated color index. Is that ok? Because of that the current algorithm evaluating color factors for diagrams would evaluate such vertex to 0 since
```
Delta[ct2, ct3] Lam[ct1, ct3, ct2] = Lam[ct1, ct2, ct2] = 0
```
as generators are traceless.

**Comment by Expander** [comment]
Yes, that may be, but there's no need to worry. :) The SMSU3 is a testing model that I've created to test the calculation of gauge coupling threshold corrections. So, it is no physically viable model and there may be inconsistencies.

**Comment by wkotlarski** [comment]
Thanks!
