### ISSUE TITLE
line shift in test_CMSSM_librarylink_slha

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#189]
If someone has a moment, could you look at the test `test/test_CMSSM_librarylink_slha.sh` on `FlexibleDecay-merge_upstream2`. I'm not sure why it fails. I think that some lines are shifted.

**Comment by Expander** [comment]
should be fixed now.

**Comment by wkotlarski** [comment]
Oh, thanks a lot. That was simple. Sorry about that.
