### ISSUE TITLE
error in test_flexiblesusy-config.sh

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#192]
@Expander, in decays we include files from template directory, e.g.
```
 #include "templates/sm_h_decays/decay_H_to_ZZ.cpp"
```
This works fine except for `test_flexiblesusy-config.sh`, which fails with a following error
```
test/SM/SM_decays.cpp:5393:10: fatal error: templates/sm_h_decays/decay_H_to_ZZ.cpp: No such file or directory
 #include "templates/sm_h_decays/decay_H_to_ZZ.cpp"
```
Do you have some advice what to do with it? Maybe you'd like me to move those includes from template?

**Comment by Expander** [comment]
Yes, please move this "model-independent" code to the `src/` directory. After the meta code has generated the C++ code (using files from the `templates/` directory), the `templates/` directory should no longer be necessary.

But I admit the name `templates/` is a bit misleading. It refers to "meta code templates" and not to "C++ templates".

One other thing, though: Can you please rename the included file to have the extension `.hpp`? Please don't include `.cpp` files.

**Comment by Expander** [comment]
The other option would be to move the files into `model_specific/SM_decays/h_decays/`, as these corrections seem to be SM-specific. This would probably be a bit cleaner and in the line with the other SM- and MSSM-specific corrections. :)

**Comment by wkotlarski** [comment]
One thing is that those are not really headers. They contain template specialization which go into `_decays.cpp` file. It basically part of `_decays.cpp` that I don't want to keep in `_decays.cpp` because it makes the file long and unreadable.

**Comment by Expander** [comment]
I see. What about renaming them to `.ipp` then?

**Comment by wkotlarski** [comment]
Should I move them to `src` or `model_specific`? These are not specific to SM, only to SM subpart of BSM.

**Comment by Expander** [comment]
Personally, I'd move them to `model_specific/`, because this seems most reasonable/clean to me.

**Comment by Expander** [comment]
Note, that you need to add them to the default included modules:
~~~
--- a/configure
+++ b/configure
@@ -2758,7 +2758,7 @@ get_model_specific_corrections() {
     local math_cmd="${2:-math}"
 
     # always build SM, because it is needed for the effective couplings module
-    local ho="SM"
+    local ho="SM SM_decays"
 
     [ -e "${model_file}" ] || {
         >&2 echo "Error: file \"${model_file}\" does not exist!"
~~~

**Comment by wkotlarski** [comment]
But this would require creating a `module.mk` file with one-line that adds to include path. Is that what you want?

**Comment by Expander** [comment]
Yes, that's true. Personally, I don't mind having such an extra `module.mk`.

**Comment by wkotlarski** [comment]
With this setup `make` tries also to create `model_specific/sm_h_decays/libmodel_specific_sm_h_decays.a`.

**Comment by Expander** [comment]
Hmm, maybe then you have a bug in the created `modue.mk` file?

Please have a look at the header-only "module" `slhaea/` which only contains a header file. If I understand correctly, this is analogous to your case.

**Comment by wkotlarski** [comment]
This happens even with empty `model_specific/sm_h_decays/module.mk`.

**Comment by Expander** [comment]
Sorry, you are right, this is non necessarily a bug on your side. The reason may be these lines, that one can find in several files:
~~~
MOD@CLASSNAME@_MOD := @MODEL_SPECIFIC_MODULES@
MOD@CLASSNAME@_DEP := $(patsubst %,model_specific/%,$(MOD@CLASSNAME@_MOD))
MOD@CLASSNAME@_INC := $(patsubst %,-Imodel_specific/%,$(MOD@CLASSNAME@_MOD))
MOD@CLASSNAME@_LIB := $(foreach M,$(MOD@CLASSNAME@_MOD),model_specific/$M/libmodel_specific_$M$(MODULE_LIBEXT))
~~~
The last line creates a "library" name for the model-specific modules. If any executable depends on this "library", then make tries to create it. Could you please run
~~~
make --debug
~~~
to see which target needs your non-existing "library"?

**Comment by wkotlarski** [comment]
Does [this](https://github.com/FlexibleSUSY/FlexibleSUSY/files/4518837/make_debug.txt) help?

**Comment by Expander** [comment]
Would you mind printing:
~~~
make print-ALLLIB
grep ALLLIB `find . -name '*.mk'`
~~~

**Comment by wkotlarski** [comment]
```
ALLLIB = src/libflexisusy.a models/SM/libSM.a test/SOFTSUSY/libSOFTSUSY.a test/libtest.a model_specific/MSSM_higgs/libmodel_specific_MSSM_higgs.a model_specific/MSSM_thresholds/libmodel_specific_MSSM_thresholds.a model_specific/NMSSM_higgs/libmodel_specific_NMSSM_higgs.a model_specific/SM/libmodel_specific_SM.a model_specific/SM_thresholds/libmodel_specific_SM_thresholds.a model_specific/SplitMSSM/libmodel_specific_SplitMSSM.a
```
and
```
./test/SOFTSUSY/module.mk:ALLLIB += $(LIBSOFTSUSY)
./test/SM/module.mk:ALLLIB += $(LIBSM)
./test/module.mk:ALLLIB += $(LIBTEST)
./src/module.mk:ALLLIB += $(LIBFLEXI)
./fflite/module.mk:ALLLIB += $(LIBFFLITE)
./model_specific/MSSM_higgs/module.mk:ALLLIB += $(LIB_model_specific_MSSM_higgs)
./model_specific/MSSM_thresholds/module.mk:ALLLIB += $(LIB_model_specific_MSSM_thresholds)
./model_specific/SplitMSSM/module.mk:ALLLIB += $(LIB_model_specific_SplitMSSM)
./model_specific/SM_thresholds/module.mk:ALLLIB += $(LIB_model_specific_SM_thresholds)
./model_specific/SM/module.mk:ALLLIB += $(LIB_model_specific_SM)
./model_specific/NMSSM_higgs/module.mk:ALLLIB += $(LIB_model_specific_NMSSM_higgs)
./models/fmssm/module.mk:ALLLIB += $(LIBFMSSM)
./models/MRSSM2/module.mk:ALLLIB += $(LIBMRSSM2)
./models/fmssmn/module.mk:ALLLIB += $(LIBFMSSMN)
./models/CMSSM/module.mk:ALLLIB += $(LIBCMSSM)
./models/MSSM/module.mk:ALLLIB += $(LIBMSSM)
./models/SM/module.mk:ALLLIB += $(LIBSM)
./models/THDMII/module.mk:ALLLIB += $(LIBTHDMII)
./addons/test_call_tsil/module.mk:ALLLIB += $(LIBtest_call_tsil)
./addons/GM2Calc/module.mk:ALLLIB += $(LIBGM2Calc)
```

**Comment by Expander** [comment]
Strange, the library is not in any of the output.

Could you please paste your `model_specific/sm_h_decays/module.mk` file?

**Comment by wkotlarski** [comment]
Now I'm using this. It's copy of `slhaea/module.mk`
```
DIR          := sm_h_decays    
MODNAME      := sm_h_decays    
    
SLHAEA_HDR   :=    
    
SLHAEA_MK    := \    
      $(DIR)/module.mk    
    
SLHAEA_INSTALL_DIR := $(INSTALL_DIR)/$(DIR)    
    
.PHONY:         all-$(MODNAME) clean-$(MODNAME) distclean-$(MODNAME)    
    
all-$(MODNAME):    
      @true    
    
ifneq ($(INSTALL_DIR),)    
install-src::    
      $(Q)install -d $(SLHAEA_INSTALL_DIR)    
      $(Q)install -m u=rw,g=r,o=r $(SLHAEA_HDR) $(SLHAEA_INSTALL_DIR)    
      $(Q)install -m u=rw,g=r,o=r $(SLHAEA_MK) $(SLHAEA_INSTALL_DIR)    
endif    
    
clean-$(MODNAME):    
      @true    
    
distclean-$(MODNAME): clean-$(MODNAME)    
    
clean::         clean-$(MODNAME)    
    
distclean::     distclean-$(MODNAME)    
```

**Comment by Expander** [comment]
That looks ok. Could you please rename the variables so that they are unique? `SLHAEA_MK` is for example already defined in `slhaea/module.mk` etc. :)

Could you please print:
~~~
make print-ALLEXE
~~~

**Comment by wkotlarski** [comment]
Ofc, the naming was just temporary :)
```
ALLEXE = config/depgen.x models/SM/run_SM.x models/SM/run_cmd_line_SM.x models/SM/scan_SM.x test/SOFTSUSY/run_softsusy.x test/SOFTSUSY/run_softpoint.x
```

**Comment by Expander** [comment]
Sorry, I'm standing on the tube now... Could you please print the output of
~~~
make -d
~~~

**Comment by wkotlarski** [comment]
[That](https://github.com/FlexibleSUSY/FlexibleSUSY/files/4519118/make_debug.txt)'s the output. It's very large. But this can wait. No hurry if you're busy. We can go back to this tomorrow.

**Comment by Expander** [comment]
Ah, now I see the problem! :)
In `models/SM/module.mk` there is the dependency
~~~
$(DIR)/%.x: $(DIR)/%.o $(LIBSM) $(MODSM_LIB) $(LIBFLEXI) ...
~~~
Here `$(MODSM_LIB)` is constructed at the top. It contains one `.a` file for every dependency from `model_specific/<...>/`. I.e. it contains `model_specific/H_SM_decays/libmodel_specific_H_SM_decays.a`.

In other words, it is assumed that all "model-specific" modules create a library that gets linked to the executable. This is not what we want. :)

Probably the easiest thing is indeed to put it into the `src/` directory. Sorry for the wurstelei. :)

**Comment by wkotlarski** [comment]
Thanks! Now it works.
