### ISSUE TITLE
test fails

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#201]
[test_run_examples.sh.log](https://github.com/FlexibleSUSY/FlexibleSUSY/files/4589874/test_run_examples.sh.log)

**Comment by Expander** [comment]
Thanks for the catch!

**Comment by wkotlarski** [comment]
[test_run_examples.sh.log](https://github.com/FlexibleSUSY/FlexibleSUSY/files/4592564/test_run_examples.sh.log)

**Comment by Expander** [comment]
Thanks again!

**Comment by wkotlarski** [comment]
[noch einmal](https://github.com/FlexibleSUSY/FlexibleSUSY/files/4593792/test_run_examples.sh.log)
