### ISSUE TITLE
Cannot build libcollier_wrapper on MacOS

### ISSUE THREAD

**Issue by Expander** [FlexibleSUSY/FlexibleSUSY#203]
@uukhas MacOS (see travis-ci output) has a problem to build `libcollier_wrapper`: It tries to compile `libcollier_wrapper.f90`, instead of `libcollier_wrapper.F90`.

I stumbled upon such an issue on MacOS in the past. The reason is that some MacOS file systems do not distinguish between upper/lower case letters. I have the feeling the same is happening here.

Probably a simple renaming of `libcollier_wrapper.f90` would solve this issue. Would you mind having a look at this?

**Comment by uukhas** [comment]
Yes, it was done in #205 by renaming from `.F90` to `.cpp`.
