### ISSUE TITLE
Why always Start?

### ISSUE THREAD

**Issue by uukhas** [FlexibleSUSY/FlexibleSUSY#213]
What do you think about the possibility to *cache* somehow the hash-information about all files in `SARAH` directory, and hash of the `SARAH` output files, saved by `FlexibleSUSY` in order to speed-up the n-th rerun of the code generation. 

We potentially can identify, what kind of internal things is initialized by `Start[<model>]`and then save it somewhere in order to save time next meta-rerun for this model.

Or, maybe, something like this already exist somewhere?

**Comment by Expander** [comment]
That's a great idea! In principle we need only to cache the `Output/` directory, that is created by `SARAH` (within the `FlexibleSUSY/` home directory).
