### ISSUE TITLE
failing collier tests

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#217]
@uukhas It doesn't look like my fault...
```
Running 8 test cases...
Entering test module "test_loopfunctions"
test/test_loopfunctions.cpp(13): Entering test case "test_A0"
Loop library should be initialized before first usage.
Setting default library.
                                                            
         *******************************************        
         *              C O L L I E R              *        
         *                                         *        
         *        Complex One-Loop Library         *        
         *      In Extended Regularizations        *        
         *                                         *        
         *    by A.Denner, S.Dittmaier, L.Hofer    *        
         *                                         *        
         *              version 1.2.4              *        
         *                                         *        
         *******************************************        
                                                            
test/test_loopfunctions.cpp(13): Leaving test case "test_A0"; testing time: 400us
test/test_loopfunctions.cpp(21): Entering test case "test_B0"
test/test_loopfunctions.cpp(30): error: in "test_B0": check model.B0(0., 0., 0.) == 0. has failed [9.2103403719761818 != 0]
test/test_loopfunctions.cpp(21): Leaving test case "test_B0"; testing time: 120us
test/test_loopfunctions.cpp(41): Entering test case "test_B1"
test/test_loopfunctions.cpp(48): error: in "test_B1": check model.B1(0., 0., 0.) == 0. has failed [-4.6051701859880909 != 0]
test/test_loopfunctions.cpp(41): Leaving test case "test_B1"; testing time: 79us
test/test_loopfunctions.cpp(54): Entering test case "test_B00"
test/test_loopfunctions.cpp(54): Leaving test case "test_B00"; testing time: 50us
test/test_loopfunctions.cpp(63): Entering test case "test_B22"
test/test_loopfunctions.cpp(63): Leaving test case "test_B22"; testing time: 49us
test/test_loopfunctions.cpp(72): Entering test case "test_H0"
test/test_loopfunctions.cpp(72): Leaving test case "test_H0"; testing time: 51us
test/test_loopfunctions.cpp(81): Entering test case "test_F0"
test/test_loopfunctions.cpp(81): Leaving test case "test_F0"; testing time: 48us
test/test_loopfunctions.cpp(90): Entering test case "test_G0"
test/test_loopfunctions.cpp(90): Leaving test case "test_G0"; testing time: 48us
Leaving test module "test_loopfunctions"; testing time: 913us

*** 2 failures are detected in the test module "test_loopfunctions"
```

**Comment by uukhas** [comment]
I would be happy if you tell:
- how did you configure `FlexibleSUSY`;
- how did you run these tests.

**Comment by wkotlarski** [comment]
This is setup from action
```
cd FlexibleSUSY
./configure --with-cxx=$CXXCOMPILER --with-math-cmd=/usr/local/Wolfram/WolframEngine/12.1/Executables/math --with-optional-modules=test --with-models=\$(echo $MODELS| tr ' ' ',') --with-loop-libraries=collier,looptools --with-looptools-incdir=/LoopTools-$LOOPTOOLS_VERSION/include --with-looptools-libdir=/LoopTools-$LOOPTOOLS_VERSION/lib64 --with-collier-incdir=/COLLIER/include --with-collier-libdir=/COLLIER/lib"
 ```
Tests
```
VERBOSE=1 make -j2 execute-meta-tests
VERBOSE=1 make -j2 alltest
FLEXIBLESUSY_LOOP_LIBRARY=0 VERBOSE=1 make -j2 execute-compiled-tests execute-shell-tests && make clean-test-log
FLEXIBLESUSY_LOOP_LIBRARY=1 VERBOSE=1 make -j2 execute-compiled-tests execute-shell-tests && make clean-test-log
FLEXIBLESUSY_LOOP_LIBRARY=2 VERBOSE=1 make -j2 execute-compiled-tests execute-shell-tests && make clean-test-log
FLEXIBLESUSY_LOOP_LIBRARY=3 VERBOSE=1 make -j2 execute-compiled-tests execute-shell-tests && make clean-test-log
```

**Comment by uukhas** [comment]
For me this setup on development branch doesn't even test `test_loopfunctions`.

If I make it explicitly (with the `conan` help):
```
make test/test_loopfunctions.x
Building test/test_loopfunctions.o
In file included from test/test_loopfunctions.cpp:6:0:
src/wrappers.hpp:31:10: fatal error: Eigen/Core: No such file or directory
 #include <Eigen/Core>
          ^~~~~~~~~~~~
compilation terminated.
Makefile:248: recipe for target 'test/test_loopfunctions.o' failed
make: *** [test/test_loopfunctions.o] Error 1
```

**Comment by Expander** [comment]
> For me this setup on development branch doesn't even test `test_loopfunctions`.

Could it be that you've not configured with `--with-optional-modules=test` and `--with-models=CMSSM`?

**Comment by uukhas** [comment]
Exactly! I have configured with default `SM` only.

**Comment by Expander** [comment]
Just for the physics: `B0` and `B1` are IR divergent for `p = m1 = m2 = 0`. `LoopTools` and `SOFTSUSY` return `0` in this case to protect against `NaN`s. It seems `COLLIER` returns something different here. It may be related to the internally used IR regulator value?

@uukhas Do you set the IR regulator to some specific value? From the manual (https://arxiv.org/abs/1604.06792) I find that they can be set via
~~~
SetDeltaIR cll(delta1,delta2)
SetMuIR2 cll(mu2)
~~~

**Comment by uukhas** [comment]
They have default values. I do not change them at this version of `COLLIER` wrapper.

**Comment by Expander** [comment]
Ok, thanks for the info!

To fix this, I see two ways:

* We disable these two tests only for `SOFTSUSY`, `LoopTools`, `FFlite`. I.e., we don't run these two tests for `COLLIER`.
* We modify the IR regulators of `COLLIER` such that the tests pass.

What is your opinion?

**Comment by uukhas** [comment]
I would suggest to disable these two points for `COLLIER` and keep default values as they are.

**Comment by Expander** [comment]
Yes, I also think this would be best, because I'm not sure about the physics implications of modifying the IR regulators.

**Comment by uukhas** [comment]
This should solve the problem:
```diff
diff --git a/test/test_loopfunctions.cpp b/test/test_loopfunctions.cpp
index 9734a9703..044f4bab0 100644
--- a/test/test_loopfunctions.cpp
+++ b/test/test_loopfunctions.cpp
@@ -3,6 +3,7 @@
 #define BOOST_TEST_MODULE test_loopfunctions
 
 #include <boost/test/unit_test.hpp>
+#include "loop_libraries/loop_library.hpp"
 #include "wrappers.hpp"
 
 #define private public
@@ -27,7 +28,9 @@ BOOST_AUTO_TEST_CASE( test_B0 )
    const double p2 = Sqr(p);
    model.set_scale(scale);
 
-   BOOST_CHECK_EQUAL(model.B0(0., 0., 0.), 0.);
+   if(Loop_library::get_type() != Loop_library::Library::Collier) {
+      BOOST_CHECK_EQUAL(model.B0(0., 0., 0.), 0.);
+   }
 
    BOOST_CHECK_CLOSE(model.B0(p2 , 0., 0.), 2. - log(p2/scale2), 1.0e-10);
    BOOST_CHECK_CLOSE(model.B0(0. , p2, 0.), 1. - log(p2/scale2), 1.0e-10);
@@ -45,7 +48,9 @@ BOOST_AUTO_TEST_CASE( test_B1 )
    const double p = 91.0;
    model.set_scale(scale);
 
-   BOOST_CHECK_EQUAL(model.B1(0., 0., 0.), 0.);
+   if(Loop_library::get_type() != Loop_library::Library::Collier) {
+      BOOST_CHECK_EQUAL(model.B1(0., 0., 0.), 0.);
+   }
 
    BOOST_CHECK_CLOSE(model.B1(p , 0., 0.), -0.5 * model.B0(p, 0., 0.), 1.0e-10);
    BOOST_CHECK_CLOSE(model.B1(0., p , p ), -0.5 * model.B0(0., p, p ), 1.0e-10);
```

**Comment by Expander** [comment]
For the record: From Eq. (7) of https://arxiv.org/abs/1604.06792 I think this issue can in principle be fixed by setting:
~~~
SetDeltaIR_cll(0.0, 0.0)
SetMuIR2_cll(1.0)    // or SetMuIR2_cll(q2)
~~~
Just for fun, one may check that. :)

**Comment by wkotlarski** [comment]
> Just for the physics: `B0` and `B1` are IR divergent for `p = m1 = m2 = 0`. `LoopTools` and `SOFTSUSY` return `0` in this case to protect against `NaN`s. It seems `COLLIER` returns something different here. It may be related to the internally used IR regulator value?
> 
> @uukhas Do you set the IR regulator to some specific value? From the manual (https://arxiv.org/abs/1604.06792) I find that they can be set via
> 
> ```
> SetDeltaIR cll(delta1,delta2)
> SetMuIR2 cll(mu2)
> ```

To be more precise, LoopTools doesn't return 0 to protect against NaNs. It returns 0 because IR divergence are also DIMREGed. In DIMREG a scaleles integral is 0 (the UV div = - IR div).

**Comment by Expander** [comment]
> To be more precise, LoopTools doesn't return 0 to protect against NaNs. It returns 0 because IR divergence are also DIMREGed. In DIMREG a scaleles integral is 0 (the UV div = - IR div).

Ah, you are right, thanks!

**Comment by wkotlarski** [comment]
> For the record: From Eq. (7) of https://arxiv.org/abs/1604.06792 I think this issue can in principle be fixed by setting:
> 
> ```
> SetDeltaIR_cll(0.0, 0.0)
> SetMuIR2_cll(1.0)    // or SetMuIR2_cll(q2)
> ```
> 
> Just for fun, one may check that. :)

I do believe that this is the better solution than what @uukhas proposed.

**Comment by Expander** [comment]
> I do believe that this is the better solution than what @uukhas proposed.

From my side, we also can go with this solution.

Can we assure that the default setting or the explicit setting of the IR regulators (as above) lead to a correct prediction that is independent of these regulators? (Are we adding real + virtual corrections correctly in all cases?) If we are not sure, then it may in deed be best to set the regulators such that the results of the loop functions agree exactly with the ones from `SOFTSUSY` and `LoopTools`. This may also save us some debugging time in the future. :)
