### ISSUE TITLE
model that does not exist

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#218]
In `model_files` we have steering file for the creation of `LHInputMSSM`. Such model doesn't exist in SARAH. If you call 
```
./createmodel -f --name=LHInputMSSM
```
you'll get
```
Searching for LHInputMSSM model file ... found model_files/LHInputMSSM/FlexibleSUSY.m.in
Searching for default SARAH model in model_files/LHInputMSSM/FlexibleSUSY.m.in ... not found
Checking SARAH model LHInputMSSM ... not found
Error: SARAH model LHInputMSSM not found in
Searching for LHInputMSSM model file ... found model_files/LHInputMSSM/FlexibleSUSY.m.in
Searching for default SARAH model in model_files/LHInputMSSM/FlexibleSUSY.m.in ... not found
Checking SARAH model LHInputMSSM ...     /home/wojciech/HEP-software/mathematica/SARAH-4.14.3/Models/
    ./sarah
not found
Error: SARAH model LHInputMSSM not found in
```
Should we remove the `model_files/LHInputMSSM` directory?

**Comment by Expander** [comment]
I'd prefer if we could keep it. It is a testing model that tests the functionality of the `LHInput[]` symbol. I've just added the default SARAH model (`MSSM`) to avoid the confusion.

**Comment by wkotlarski** [comment]
That's fine. I don't mind. I just didn't know if was suppose to be there or not. Thanks.

**Comment by pathron** [comment]
Thanks for adding the default SARAH model.  Could there be any other old model files that are missing default SARAH models or was this the only one?

**Comment by Expander** [comment]
I've fixed all remaining ones in commit 32320939a

**Comment by wkotlarski** [comment]
No. Now all models can be created. Didn't run make though.

**Comment by wkotlarski** [comment]
Fun fact. Even without last commit from @Expander, all models work. For example
```
Searching for NoYukawaMSSM model file ... found model_files/NoYukawaMSSM/FlexibleSUSY.m.in
Searching for default SARAH model in model_files/NoYukawaMSSM/FlexibleSUSY.m.in ... not found
Checking SARAH model NoYukawaMSSM ... ok
Creating model NoYukawaMSSM (SARAH model: NoYukawaMSSM)
  Creating Makefile module models/NoYukawaMSSM/module.mk ... done
  Creating start script models/NoYukawaMSSM/start.m ... done
  Creating FlexibleSUSY model file models/NoYukawaMSSM/FlexibleSUSY.m ... done
```
even though it doesn't have `FSDefaultSARAHModel` defined.

**Comment by Expander** [comment]
Sorry, I was too quick. @wkotlarski is correct, all models work so far w/o the need to specify a default SARAH model.
