### ISSUE TITLE
Beta function part of LeptoSplitMSSM take very long time

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#237]

**Comment by Expander** [comment]
Thanks for reporting! How long does it roughly take on your machine?

**Comment by wkotlarski** [comment]
Few hours. I'm timing it right now.

**Comment by wkotlarski** [comment]
E.g.
```
Fermion chains
                      (Time needed so far: 2458.89s)
```

**Comment by Expander** [comment]
I can reproduce this long run-time. However, I'm afraid this is a SARAH issue and not a problem on the FS side.

**Comment by pathron** [comment]
What is the gauge group?  SARAH can be *very* slow for some cases.

**Comment by wkotlarski** [comment]
I thinks it's the usuall one. The model file says

_Implementation of the split-MSSM with extra light 1st and 2nd    
   generation sleptons.  The convention of arXiv:1407.4081 is used._

Also, ```Model`Authors = "F.Esser,A.Voigt";``` ;)

**Comment by Expander** [comment]
I believe the main reason for the long run-time is the complexity of the Lagrangian and thus the large amount of couplings that it has. Fabian Esser saw these long run-times before, as far as I remember. (Mathematica even crashed on his machine from time to time when building this model.)

BTW, this model represents an EFT in the only remaining reasonable corner of the MSSM parameter space, where stops are heavy (for the Higgs mass) and 1st and 2nd generation sleptons are light (for g-2). This may thus be an interesting model for GAMBIT to study, I think. :)

**Comment by pathron** [comment]
Thanks for the suggestion.  It might have been a model we could use for our g-2 paper, but a bit late for that.  By the way GAMBIT is public and an open community now.  If there are models you want GAMBIT global fits for you can propose joint projects with GAMBIT members, just so you know :).  Or maybe that is what you are trying to do now ?

**Comment by wkotlarski** [comment]
Should we close it?

**Comment by Expander** [comment]
Yes, please close it, as it is not a FS issue.
