### ISSUE TITLE
Collier release

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#242]
Should we make a 2.5 release with Collier interface? This will make referring to it simpler.

**Comment by Expander** [comment]
That's an excellent idea!

**Comment by Expander** [comment]
Can the current development branch be made a release?

@wkotlarski Could you please document the change `Temporary -> FSTemporary`?

**Comment by wkotlarski** [comment]
Done in 21acb9a6fbb32be1590482765347469c06291e20.

**Comment by wkotlarski** [comment]
@uukhas? Are you ok with this? It's your child.

**Comment by Expander** [comment]
`test_E6SSM_CXXDiagrams.m.log` currently fails. Do you know why?

**Comment by wkotlarski** [comment]
No. On github it works
```
test/test_E6SSM_CXXDiagrams.m                                        OK
```

**Comment by uukhas** [comment]
The interface seems to be working, so I am ok with this.

**Comment by Expander** [comment]
I'm testing `test/test_E6SSM_CXXDiagrams.m` just now on my machine.

@wkotlarski @uukhas are you ok with the current version of the `CHANGES.rst`? I've updated it.

Besides this, I'd leave the other PRs for a later version (2.6 or later).

**Comment by Expander** [comment]
Ok, it passes on my machine (and also in the nightly test from last night).
So, we are in principle ready to release, if you don't have any additions.

**Comment by Expander** [comment]
FlexibleSUSY 2.5.0 has just been released! :)

Thank you all for contributing, in particular @uukhas for the new loop function interface!
