### ISSUE TITLE
CMSSM_librarylink fail on CI

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#250]
@Expander, I was checking why the test fails on docker. If I run it on my system, it's fine. But on the docker image I get
```
/usr/local/Wolfram/WolframEngine/12.1/SystemFiles/Kernel/Binaries/Linux-x86-64/WolframKernel: symbol lookup error: /FlexibleUpstream/models/CMSSM/CMSSM_librarylink.so: undefined symbol: _gfortran_string_len_trim
```
Any idea why? Should we link `-lgfortran` to `CMSSM_librarylink.so`. But then why doesn't it fail on my machine directly, only through docker?

**Comment by Expander** [comment]
Maybe on your machine these symbols are located in a library that we do link to `CMSSM_librarylink.so`. Would you mind trying the following patch? It just links `$(FLIBS)` to the `.so` file in addition.
~~~.patch
diff --git a/templates/module.mk.in b/templates/module.mk.in
index 374717ef3..bc3900034 100644
--- a/templates/module.mk.in
+++ b/templates/module.mk.in
@@ -332,7 +332,7 @@ $(DIR)/%.x: $(DIR)/%.o $(LIB@CLASSNAME@) $(MOD@CLASSNAME@_LIB) $(LIBFLEXI) $(fil
 
 $(LL@CLASSNAME@_LIB): $(LL@CLASSNAME@_OBJ) $(LIB@CLASSNAME@) $(MOD@CLASSNAME@_LIB) $(LIBFLEXI) $(filter-out -%,$(LOOPFUNCLIBS)) $(FUTILIBS)
                @$(MSG)
-               $(Q)$(LIBLNK_MAKE_LIB_CMD) $@ $(CPPFLAGS) $(CFLAGS) $(call abspathx,$(ADDONLIBS) $^) $(filter -%,$(LOOPFUNCLIBS)) $(GM2CALCLIBS) $(HIMALAYALIBS) $(GSLLIBS) $(THREADLIBS) $(LDLIBS) $(LLLIBS) $(FUTILIBS)
+               $(Q)$(LIBLNK_MAKE_LIB_CMD) $@ $(CPPFLAGS) $(CFLAGS) $(call abspathx,$(ADDONLIBS) $^) $(filter -%,$(LOOPFUNCLIBS)) $(GM2CALCLIBS) $(HIMALAYALIBS) $(GSLLIBS) $(THREADLIBS) $(LDLIBS) $(LLLIBS) $(FUTILIBS) $(FLIBS)
 
 ALLDEP += $(LIB@CLASSNAME@_DEP) $(EXE@CLASSNAME@_DEP)
 ALLSRC += $(LIB@CLASSNAME@_SRC) $(EXE@CLASSNAME@_SRC)
~~~

**Comment by wkotlarski** [comment]
This solve this problem. But there's another on
```
----------------
##9       #:4   <== solver
##9       #:4   ==> algorithm
@                                                     @@
##9       #:5   <== (0
##9       #:5   ==> (1
@                                                     @@
##9       #:7   <== all)
##9       #:7   ==> two_scale,
@                                                     @@
##9             <==
##9       #>8   ==> 2 = semi-analytic)
@ Line 9 in file "test/test_CMSSM_librarylink_slha.out1.spc~" is shorter than expected!
```
Could it be that the problem is that, for example, in one file there's
```
     2     1.00000000E+00   # solver (0 = all)
```
while in other
```
    2   1                    # algorithm (1 = two_scale, 2 = semi-analytic)
```

**Comment by wkotlarski** [comment]
This solves that problem. There's one more though. Seems like the library link call reorders entries in `DECAY` block. It doesn't happen on my machine using Mathematica, but on docker with Wolfram Engine it does.

**Comment by wkotlarski** [comment]
`out1.spc~`
```
DECAY        25     3.27158897E-03   # hh(1) decays
     2.89455493E-02   2          -4         4  # BR(hh(1) -> barFu(2) Fu(2))
```
```
`out2.spc~`
```
DECAY        25     3.27158897E-03   # hh(1) decays
     0.00000000E+00   2          -4         2  # BR(hh(1) -> barFu(2) Fu(1))
```

**Comment by Expander** [comment]
> This solves that problem.

Thanks for testing! I've fixed it in the `development` branch.

**Comment by Expander** [comment]
> Seems like the library link call reorders entries in `DECAY` block.

That's strange. Do you write the entries in the same way in the librarylink and in the C++ interface?

**Comment by wkotlarski** [comment]
That's a very good question. I'm totally unfamiliar with the library link part of decays and FS in general. I'm looking into it right now.

**Comment by wkotlarski** [comment]
Could it be that `slha_io.set_block` reorder entries? I'm printing the order from inside of `CMSSM_slha_io::set_decay_block(const Decays_list& decays_list)` which gives
```
barFu(2) Fu(2) 
barFd(3) Fd(3) 
barFd(2) Fd(3) 
barFd(2) Fd(1) 
...
```
The `test/test_CMSSM_librarylink_slha.out2.spc`, which is an output not using mathlink, then have
```
DECAY        25     3.27158897E-03
     0.00000000E+00   2          -4         2
     0.00000000E+00   2          -2         4
     7.39121619E-01   2          -5         5
```
while the `test/test_CMSSM_librarylink_slha.out1.spc`
```
DECAY        25     3.27158897E-03
     2.89455493E-02   2          -4         4
     7.39121619E-01   2          -5         5
     0.00000000E+00   2          -3         5
```
So it seams that mathlink part does preserve the order of entries. While the c++ print out doesn't.

**Comment by Expander** [comment]
Hmm, `set_block()` has an optional parameter `position`. Are you setting this parameter to some value, or are you leaving the default?

**Comment by wkotlarski** [comment]
Default. We're calling
```cpp
slha_io.set_block(decay);
```

**Comment by Expander** [comment]
Is `decay` a stream object?

**Comment by wkotlarski** [comment]
yes

**Comment by Expander** [comment]
Then the following is called:
~~~.cpp
void SLHA_io::set_block(const std::string& lines, Position position)
{
   SLHAea::Block block;
   block.str(lines);

   data->erase(block.name());

   if (position == front) {
      data->push_front(block);
   } else {
      data->push_back(block);
   }
}
~~~
I can't see how this should reorder blocks.

**Comment by wkotlarski** [comment]
Yeah, I know :cry:

**Comment by Expander** [comment]
Just for my stupidity, did you check that the `decay` stream objects are properly ordered?

**Comment by Expander** [comment]
Hmm, even if `push_front()` or `push_back()` do reorder/sort things, why the heck is the resulting order different in the two cases?

**Comment by wkotlarski** [comment]
This is the beginning of decay from `CMSSM_slha_io::set_decay_block`
```
     2.89455493E-02   2          -4         4  # BR(hh(1) -> barFu(2) Fu(2))
     7.39121619E-01   2          -5         5  # BR(hh(1) -> barFd(3) Fd(3))
     0.00000000E+00   2          -3         5  # BR(hh(1) -> barFd(2) Fd(3))
```
This is what is printed to `test/test_CMSSM_librarylink_slha.out2.spc`
```
     0.00000000E+00   2          -4         2
     0.00000000E+00   2          -2         4
     7.39121619E-01   2          -5         5
```

**Comment by wkotlarski** [comment]
> Hmm, even if `push_front()` or `push_back()` do reorder/sort things, why the heck is the resulting order different in the two cases?

Maybe because the mathematica printout and c++ printout are two different functions. The mathematica one is defined in `meta/FSMathLink.m` (function `PutDecayTableEntries`).

**Comment by Expander** [comment]
Interestingly, I cannot reproduce this error on my machine:
~~~
$ ./test/test_CMSSM_librarylink_slha.sh
Wolfram Language 12.0.0 Engine for Linux x86 (64-bit)
Copyright 1988-2019 Wolfram Research, Inc.

In[1]:= ================================
FlexibleSUSY 2.5.0
CMSSM
http://flexiblesusy.hepforge.org
================================

FSCMSSM::info: Warning: Check FlexibleSUSY[31]:

FSCMSSM::info: Currently configured values are 0 (=softsusy).

FSCMSSM::info: Setting default library.

General::stop: Further output of FSCMSSM::info
     will be suppressed during this calculation.
Warning: Check FlexibleSUSY[31]:
Currently configured values are 0 (=softsusy).
Setting default library.

+++  Files "./test/test_CMSSM_librarylink_slha.out1.spc" and "./test/test_CMSSM_librarylink_slha.out2.spc" are equal
Test result: OK
~~~
Could it be that we're somehow relying on a certain STL implementation-defined behavior, which is not actually guaranteed? (I.e. some kind of sorting or so.)?

**Comment by Expander** [comment]
I cannot reproduce this misbehavior unfortunately:
~~~
$ FLEXIBLESUSY_LOOP_LIBRARY=1 ./test/test_CMSSM_librarylink_slha.sh
+++  Files "./test/test_CMSSM_librarylink_slha.out1.spc" and "./test/test_CMSSM_librarylink_slha.out2.spc" are equal
Test result: OK
~~~

~~~
$ FLEXIBLESUSY_LOOP_LIBRARY=2 ./test/test_CMSSM_librarylink_slha.sh
+++  Files "./test/test_CMSSM_librarylink_slha.out1.spc" and "./test/test_CMSSM_librarylink_slha.out2.spc" are equal
Test result: OK
~~~

**Comment by Expander** [comment]
It appears to me, that both the LibraryLink and the command line interface actually run the same code:

LibraryLink:
~~~.cpp
      slha_io.set_dcinfo(decays.get_problems());
      if (show_decays) {
         slha_io.set_decays(decays.get_decay_table());
      }
~~~

`run_CMSSM.cpp`:
~~~.cpp
   slha_io.set_dcinfo(decays_problems);
   if (!decays_problems.have_problem() || force_output) {
      slha_io.set_decays(decays.get_decay_table());
   }
~~~

From this information, I would guess that the problem should lie within the `decays` object or the `set_decays()` function. 

Just for my understanding: Do you have checked, that the `decays` objects that are printed are actually identical? (This is what I've understood from your message.) I.e. the `Table_type decay_table` contains the same elements in the same order?

**Comment by wkotlarski** [comment]
Could you try the same on the docker image? You'd have to download it as `docker pull navir/opensuseleap-for-flexiblesusy`. Hope you have lincense for Wolfram Engine, then you have to mount it during running in a proper place (mine is in $HOME/Licensing)
```
docker run -it -v $HOME/Licensing:/root/.WolframEngine/Licensing navir/opensuseleap-for-flexiblesusy
```
Then you will see the problem. All FlexilbeSUSY dependecies are instaled on the image. Apart from FS itself.

**Comment by wkotlarski** [comment]
Proof I'm not crazy [test_CMSSM_librarylink_slha.sh.log](https://github.com/FlexibleSUSY/FlexibleSUSY/files/4893304/test_CMSSM_librarylink_slha.sh.log)

**Comment by Expander** [comment]
I was never in doubt! :)

**Comment by Expander** [comment]
Sorry, I'm not familiar with using docker. Which commands do I have to execute in order to reproduce the error?

I ran
~~~
docker run -it -v $HOME/Licensing:/root/.WolframEngine/Licensing navir/opensuseleap-for-flexiblesusy
~~~
which gives me a prompt `#`. However, when I try to run `math`, I get:
~~~
90be1a987288:/ # math
Wolfram Language 12.1.0 Engine for Linux x86 (64-bit)
Copyright 1988-2020 Wolfram Research, Inc.

Wolfram Language 12.1.0 Engine cannot find a valid password.

For automatic Web Activation enter your activation key
(enter return to skip Web Activation): 
~~~
Is there no WolframEngine license installed on the image?

**Comment by wkotlarski** [comment]
No. You have to bring in your own license. Assuming file structure `/some/dir/on/your/system/mathpass` you then do
```
docker run -it -v /some/dir/on/your/system:/root/.WolframEngine/Licensing navir/opensuseleap-for-flexiblesusy
```

**Comment by Expander** [comment]
Thanks for the explanation! However, this does not work as expected. On my machine the license is under `$HOME/.WolframEngine/Licensing/mathpass`. When I run:
~~~
$ docker run -it -v $HOME/.WolframEngine/Licensing:/root/.WolframEngine/Licensing navir/opensuseleap-for-flexiblesusy
~~~
then the `mathpass` is in the expected directory:
~~~
# ls /root/.WolframEngine/Licensing/
mathpass
~~~
However, running `math` then yields:
~~~
# math
Wolfram Language 12.1.0 Engine for Linux x86 (64-bit)
Copyright 1988-2020 Wolfram Research, Inc.

Wolfram Language 12.1.0 Engine cannot find a valid password.
...
You will need to get a password from your
license certificate or from Wolfram Research
(http://register.wolfram.com).
Machine name:	[...]
MathID:	[...]
~~~
Do I have to somehow map the `Machine name` and the `MathID` in the docker image to the one on my machine?

**Comment by Expander** [comment]
How do you usually download/build/run FS in this docker environment? Do you "log in" and then run everything "by hand", or do you use a script or so?

**Comment by wkotlarski** [comment]
I usually don't use it. So everything has to be done by hand. In CI we run github specific [script](https://github.com/FlexibleSUSY/FlexibleSUSY/blob/development/.github/workflows/tests.yml).

**Comment by Expander** [comment]
I've now build the CMSSM within the docker image using the following commands:
~~~.sh
docker run -it -v $HOME/mathematica/Licensing:/root/.WolframEngine/Licensing navir/opensuseleap-for-flexiblesusy
~~~
Inside docker:
~~~.sh
git clone https://github.com/FlexibleSUSY/FlexibleSUSY
cd FlexibleSUSY
git fetch origin FlexibleDecay-merge_upstream2:FlexibleDecay-merge_upstream2
git checkout FlexibleDecay-merge_upstream2

./createmodel --name=CMSSM -f

CXXCOMPILER=g++

./configure \
    --with-cxx=$CXXCOMPILER \
    --with-models=CMSSM \
    --with-loop-libraries=collier,looptools \
    --with-looptools-incdir=/LoopTools-$CXXCOMPILER/include \
    --with-looptools-libdir=/LoopTools-$CXXCOMPILER/lib64 \
    --with-collier-incdir=/COLLIER/include \
    --with-collier-libdir=/COLLIER/lib \
    --with-himalaya-incdir=/Himalaya-$CXXCOMPILER/include \
    --with-himalaya-libdir=/Himalaya-$CXXCOMPILER/lib64 \
    --with-optional-modules=test

make -j2 VERBOSE=1
~~~
When I then run the test inside docker, it fails as you describe:
~~~.sh
# FLEXIBLESUSY_LOOP_LIBRARY=1 test/test_CMSSM_librarylink_slha.sh
Wolfram Language 12.1.0 Engine for Linux x86 (64-bit)
Copyright 1988-2020 Wolfram Research, Inc.

In[1]:= ================================
FlexibleSUSY 2.5.0
CMSSM
http://flexiblesusy.hepforge.org
================================
                                                            
         *******************************************        
         *              C O L L I E R              *        
         *                                         *        
         *        Complex One-Loop Library         *        
         *      In Extended Regularizations        *        
         *                                         *        
         *    by A.Denner, S.Dittmaier, L.Hofer    *        
         *                                         *        
         *              version 1.2.5              *        
         *                                         *        
         *******************************************        
                                                            
                                                            
         *******************************************        
         *              C O L L I E R              *        
         *                                         *        
         *        Complex One-Loop Library         *        
         *      In Extended Regularizations        *        
         *                                         *        
         *    by A.Denner, S.Dittmaier, L.Hofer    *        
         *                                         *        
         *              version 1.2.5              *        
         *                                         *        
         *******************************************        
                                                            
----------------
##521     #:1   <== 2.89455493E-02
##521     #:1   ==> 0.00000000E+00
@ Absolute error = 2.8945549300e-2, Relative error = Inf
##521     #:4   <== 4
##521     #:4   ==> 2
@ Absolute error = 2.0000000000e+0, Relative error = 1.0000000000e+0
----------------
...
~~~

**Comment by Expander** [comment]
Is there some way to easily install emacs inside the docker image in order to edit some files to debug the problem? (I've not found any reasonable editor in the image. :D )

**Comment by Expander** [comment]
Just a quick update: I've printed what goes on in `set_decay_block()`: The order of the entries in `decays_list` is different between the two runs.

**Comment by Expander** [comment]
OK, I've found the issue: `Decays_list` (in `src/decay.hpp`) stores the individual decays in an `unordered_map`. When `set_decay_block()` reads the entries from this `unordered_map`, there is no guarantee that one gets the content of the map back in the order one has written to it.

When I change  `unordered_map -> map`, the test passes.

The SLHA standard does not specify the order in which the decays are written, so I think the current behaviour is OK and we may in principle simply fix the test by sorting the entries in the `DECAY` block.

On the other side, having a consistent output among all of our own routines would be best. So, the alternative would be to use `std::map` and we would never run into these kind of problems again.

What do you think?

**Comment by wkotlarski** [comment]
I've added emacs to the image. I feel dirty...

**Comment by wkotlarski** [comment]
> OK, I've found the issue: `Decays_list` (in `src/decay.hpp`) stores the individual decays in an `unordered_map`. When `set_decay_block()` reads the entries from this `unordered_map`, there is no guarantee that one gets the content of the map back in the order one has written to it.

I'm such an idiot. I've missed that. I checked to the order of writes is the same, but didn't check the container type itself. I've changed it to `map` as you suggest in 20e2adc.

**Comment by Expander** [comment]
> I've added emacs to the image. I feel dirty...

:D

**Comment by Expander** [comment]
> > OK, I've found the issue: `Decays_list` (in `src/decay.hpp`) stores the individual decays in an `unordered_map`. When `set_decay_block()` reads the entries from this `unordered_map`, there is no guarantee that one gets the content of the map back in the order one has written to it.
> 
> I'm such an idiot. I've missed that. I've checked that the order of writes is the same, but didn't check the container type itself. I've changed it to `map` as you suggest in [20e2adc](https://github.com/FlexibleSUSY/FlexibleSUSY/commit/20e2adc9967c219e05ffb8c6b5831f61b1494152).

Many thanks, I'm perfectly fine with this approach.

**Comment by wkotlarski** [comment]
Solve in 20e2adc9967c219e05ffb8c6b5831f61b1494152.
