### ISSUE TITLE
handling decay tests

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#252]
Currently, the decay code correctly handles the loop library flag when called through `run_*` or FSMathLink. As an example, in the SM, if there's no dedicated loop library, we print
```
DECAY        25     0.00000000E+00   # hh decays
```
while if we have a dedicated loop library, we print
```
DECAY        25     4.05549936E-03   # hh decays
     6.26949033E-02   2         -15        15  # BR(hh -> barFe(3) Fe(3))
    ...
```
Maybe we should print some info to one of the observable error blocks about the reason why the value of decays is 0 in the first case, but this is a secondary issue. 

The problem that we have is with tests. Decay test by itself have to check the configuration of FlexibleSUSY. This could be done in 2 two ways:

1. the level of makefile
2. the level of individual tests

The option 2 requires securing every test separately, but has an advantage that some decay tests like `h -> bbbar` can still be run.

**Comment by Expander** [comment]
Concerning the SLHA output in case decays are disabled: Personally I found the output
~~~
DECAY        25     0.00000000E+00   # hh decays
~~~
very confusing the first time I saw it like this (i.e. cut off). I would find it more natural that *no* `DECAY` block is show in case the decays are not calculated.

Concerning the configuration: I think we could provide both options easily:
* If I understand correctly, the `configure` script knows whether the decays are enabled/disabled. It could thus set a `Makefile` variable `ENABLE_DECAYS` to `yes/no`, which could be checked by the tests that like it this way.
* In addition, a preprocessor define in `config/config.h.in` could be added. The C++ tests could then enable/disable tests based on this preprocessor definition.

I guess this would allow for maximum flexibility. :)

**Comment by Expander** [comment]
> You know that g-2 does the same, right?

Well, kind of, yes. For g-2 the line entry is zero. Here, however, there is only a block head, with no block body. That confused me. :)

**Comment by pathron** [comment]
To be honest I found it confusing for both decays *and* g-2 that we we do it this way.  Having no block entry when things are not calculated would really be ideal, no?

**Comment by Expander** [comment]
OK, this would probably be ideal. Let's see how that can be achieved. We may need to restructure the code in order to do that, I guess.

**Comment by wkotlarski** [comment]
> OK, this would probably be ideal. Let's see how that can be achieved. We may need to restructure the code in order to do that, I guess.

@Expander, should I wait with any changes to it related to decays until you change other observables?

**Comment by Expander** [comment]
We could wait. But I guess in principle the observables are is somehow tangential.

**Comment by wkotlarski** [comment]
95b9a96176057919ddd6451479e693a06d74e0dd disables printing empty `DECAY` heads.

**Comment by wkotlarski** [comment]
All tests work. I'll close it now.
