### ISSUE TITLE
add polylogs of order 3 and 4

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#257]
@Expander, some analytic higher order corrections to decays require  polylogs of order 3 and 4 for complex arguments. I think we don't have them in FS but they are in your [Polylogarithm](https://github.com/Expander/polylogarithm) package. Could we bring them into FS?

**Comment by Expander** [comment]
Yes, of course! In fact, `PolyLog(3,z)` is already included in FS. I can include `PolyLog(4,z)` as well, if needed.

**Comment by Expander** [comment]
fixed in 65c4eef5f56
