### ISSUE TITLE
CI on github hangs or crashes after around 19th of every month

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#259]
CI hangs on step:
` Run compiled and shell script tests with 0`
or crashes during configure with
```
./createmodel: line 235:  1151 Segmentation fault      (core dumped) "$mathematica_kernel"  > /dev/null <<EOF
Checking SARAH model MSSM ... error
Needs["SARAH\`"];
Error: SARAH could not be loaded via Needs["SARAH`"] .
If[!ValueQ[SA\`Version], Quit[1]];
    Please install SARAH such that it can be loaded via Needs["SARAH`"] .
Quit[0];
    You can use ./install-sarah to install SARAH.
EOF
```

**Comment by wkotlarski** [comment]
@Expander, I thing I might have some new idea why this happens. This segfault is model specific! It's caused by `MSSMEFTHiggs`. What is so special about this model?

**Comment by Expander** [comment]
Hmm, there is nothing special about the `MSSMEFTHiggs`. But in principle, Mathematica is not supposed to crash, because we're not explicitly doing memory management or so. So, I think this is an actual Mathematica bug.

**Comment by wkotlarski** [comment]
Yes, you're definitely right. I was just wandering if the is something `MSSMEFTHiggs` that triggers this bug compared to other models.

**Comment by Expander** [comment]
In the past I've also noticed random crashes from time to time and could never pin-point them. :/
