### ISSUE TITLE
FlexibleSUSY error handling when number of EWSB ouputs != EWSB equations

### ISSUE THREAD

**Issue by pathron** [FlexibleSUSY/FlexibleSUSY#262]
Currently when a model file is badly written in FS such that the number of EWSB outputs is not equal to the number of EWSB equations FS just outputs an error message like

 `Error: There are 1 independent EWSB equations, but you want to fix 2

and then carries on to generate code and eventually give some cryptic compiler error.  The user may only notice the compiler error, but have no clue what the cause is.

I can't think of any cases where the code would be useful if the    the number of EWSB outputs is not equal to the number of EWSB equations, so i suggest we halt the code generation.  Alex already proposed a solution and I will make a pull request for this but adding this for discussion in case there are other opinions or other similar fixes. .`

**Comment by pathron** [comment]
Pull request here https://github.com/FlexibleSUSY/FlexibleSUSY/pull/263 will merge it if everyone is happy.

**Comment by pathron** [comment]
In an email thread Alex wrote:

> would you mind testing this patch with a model with a complicated EWSB
> sector, like the cCMSSM or the CMSSMCPV?  These models tend to have
> redundant EWSB eqs and I just want to make sure they work as before.
>

Testing these now.   Let me know if there are other models that may be affected.

**Comment by pathron** [comment]
Both of those build (and run) fine.

**Comment by Expander** [comment]
Great, many thanks for testing!
