### ISSUE TITLE
Explicit indices in SARAH`Vertex for VVVV.

### ISSUE THREAD

**Issue by uukhas** [FlexibleSUSY/FlexibleSUSY#271]
If one uses indices, which are not **explicitly** equal to `lt1, lt2, lt3, lt4`, then vertex is evaluated to zero, like here:
```Mathematica
Needs@"SARAH`";
Start@"MSSM";

Vertex@{conj[VWm[{lt1}]], VZ[{lt2}], VWm[{lt3}], VZ[{lt4}]}
Vertex@{conj[VWm[{1}]], VZ[{lt2}], VWm[{lt3}], VZ[{lt4}]}
```
First expression evaluates to 
```Mathematica
{
  {conj[VWm[{lt1}]], VZ[{lt2}], VWm[{lt3}], VZ[{lt4}]}, 
  {I g2^2 Cos[ThetaW]^2,    g[lt1, lt2] g[lt3, lt4]},
  {-2 I g2^2 Cos[ThetaW]^2, g[lt1, lt3] g[lt2, lt4]},
  {I g2^2 Cos[ThetaW]^2,    g[lt1, lt4] g[lt2, lt3]}
}
```
while the second gives 
```Mathematica
{
  {conj[VWm[{1}]], VZ[{lt2}], VWm[{lt3}], VZ[{lt4}]},
  {0, g[lt1, lt2] g[lt3, lt4]}, 
  {0, g[lt1, lt3] g[lt2, lt4]}, 
  {0, g[lt1, lt4] g[lt2, lt3]}
}
```

This is caused by ``SARAH`ExtractLorentz ``, where nobody cares about possible explicit indices. Should one be careful about this, as in #270 (this is relevant for #63)?

**Comment by uukhas** [comment]
Do we use/plan to use explicit Lorentz indices somewhere?
**No** - we can close this issue.
**Yes** (unlikely) - something(?) should be done.

**Comment by Expander** [comment]
I don't see any use case right now. Although, in principle I could imagine that using VVVV vertex with the explicit index structure may be useful. Is there a way to put a comment (or warning) into the meta code when such a vertex is treated in order to warn us when we use it next time?

**Comment by uukhas** [comment]
I think, that there is no simple way from our side to make this warning.
Me might think about some wrapper, but it might be too complicated and too slow for meta-code.

**Comment by Expander** [comment]
I see. What about a pure comment in some of our modules where you think we would probably use such a vertex next time?

**Comment by uukhas** [comment]
I cannot say right now, which modules might like to use it for sure.
Maybe the ones, which are connected to observables, like `HiggsDecays` or `NPointFunctions`.
Do you mean just some text comment in the beginning of the packages?

**Comment by Expander** [comment]
> Do you mean just some text comment in the beginning of the packages?

Yes, this is what I was thinking, after you explained that it may be difficult to do it in another way. So, we would at least have some comment to warn us.  :)

**Comment by uukhas** [comment]
It seems that I have found a way to wrap VVVV vertex and prevent an infinite loop:
```wolfram
Module[{status = True, res},
 SARAH`Vertex[f: {_, _, _, _}, opts___]/; status := (
   status = False;
   Print@SARAH`Vertex::warnVVVV;
   res = SARAH`Vertex[f, opts];
   status = True;
   res)];
SARAH`Vertex::warnVVVV = 
  "Warning: the usage of explicit indices in VVVV vertex is error prone.";
```
We just need to put it somewhere in the metacode. Maybe in the very beginning of `MakeFlexibleSUSY` function.
If the idea is accepted, then I can make a PR.

**Comment by Expander** [comment]
Thanks for investigating into this issue! But could it be that this code snipped always prints a warning? (There does not seem to be a restriction on the particles in the `Vertex` function.) Also, I'd propose to use ``Message[SARAH`Vertex::warnVVVV]`` instead of ``Print[SARAH`Vertex::warnVVVV]``, because `Message` can be disabled.

**Comment by uukhas** [comment]
This code checks now only the amount of arguments, which should be equal to 4:
```wolfram
SARAH`Vertex[f: {_, _, _, _}, opts___]
```
If we want to be 100% sure, that all of them are **Vector** particles, then I can suggest to replace it by:
```wolfram
SARAH`Vertex[f: {Repeated[_?TreeMasses`IsVector, {4}]}, opts___]
```
Also, we can be more specific about the error as well:
```wolfram
Message[SARAH`Vertex::warnVVVV, f];
...
SARAH`Vertex::warnVVVV = 
  "Warning: potential usage of explicit indices in \"`1`\" vertex is error prone.";
```
Also, everything, which is not a **ct**, **lt**, **gt** index can generate problem.
And there might be a possibility to check it for **f**, something like: remove conjugate,
remove the names of the fields, check their indices for something else from the ones mentioned above.
After this the warning will be printed only in potentially problematic cases and not always like that.

**Comment by Expander** [comment]
I'd definitely suggest to only print a warning in a problematic case. I.e. your restriction to having 4 vectors with a problematic index naming would be best. Otherwise we may stumble upon warnings that make no sense and/or don't apply.

In addition, I'd also suggest to make the warning even more explicit by explaining why the function call is problematic and/or what will go wrong. (If the message becomes too long, one could also add a Mathematica comment above the warning message to explain the reason for the warning in more detail.)

**Comment by uukhas** [comment]
Ok, thank you for this. I will prepare a PR and then we can discuss with more details about the structure of the message and implementation as well.
