### ISSUE TITLE
(probably not) an unused variable

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#275]
I'm trying to eliminate warnings from FS compilation. One of them is
```
In file included from models/SM/SM_slha_io.hpp:25:
src/for_each.hpp:40:12: warning: unused variable 'l' [-Wunused-variable]
      auto l = { (f(std::get<Is>(t)), 0)... };
```
coming from
https://github.com/FlexibleSUSY/FlexibleSUSY/blob/a6c3f4ee40782fa86a207cee3989adda975afb37/src/for_each.hpp#L40
Is this some template magic I just don't understand or is it really an unused variable?

**Comment by Expander** [comment]
This variable is indeed unused, in the sense that it is not read from. However, I'm not sure how to fix it, because I have the feeling that the r.h.s. must be assigned to something in order to be instantiated.

**Comment by wkotlarski** [comment]
I would maybe add something like that
```c++
// @todo: uncomment after the transition to c++17
// [[maybe_unused]]
```
and leave it for now.

**Comment by Expander** [comment]
I like this idea!

**Comment by wkotlarski** [comment]
Done in b3c97f167733177612d2756a21bcd18ec2130435.
