### ISSUE TITLE
broken test

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#279]
If one runs FS through mathlink, then there's no equivalent of
```
    15   1                    # calculate observables (a_muon, ...)
```
variable. This means that observables are never printed.

**Comment by Expander** [comment]
Does `FS@ModelName@CalculateObservables[]` not print the observables?

**Comment by wkotlarski** [comment]
We decided that we'll control whether observables are printed or not by passing settings to `set_extra`. But when you use mathematica interface, the settings don't know about flag 15.

**Comment by Expander** [comment]
Ah, yes, you are right. So, when a user currently uses the Mathematica interface, he decides whether to calculate the observables (using this function) or not. Maybe this design decision back then was not optimal. But anyway, do you want change it? Do you have a proposal in mind?

**Comment by wkotlarski** [comment]
How about this 93692d6a076ae55c00ced70e923fabbd950aac8b?

**Comment by Expander** [comment]
I'm not quite sure I understand what this change is supposed to do. It seems you are enforcing the observables to be calculated. Isn't this always the case? If not, then I agree with this change.

**Comment by wkotlarski** [comment]
No, it only affects printing. Mathlink part only calculated observables if one calls observables directly. Calling them directly now sets appropriate flag in settings which is then read in the printing routine telling it to print observables.

**Comment by Expander** [comment]
Ah, you're saying that the observables have not been printed before when this routine was called? Then this was a bug? :)

**Comment by wkotlarski** [comment]
Yes. It broke CMSSM library link test.

**Comment by Expander** [comment]
Ah, now I understand, sorry. :) Please feel free to merge you change then.
(I made some comments, though.)
