### ISSUE TITLE
fix floating point comparison?

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#286]
Would you like me to fix it the following and similar warnings?
```
models/SM/SM_two_scale_low_scale_constraint.cpp:201:27: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
   if (qedqcd.get_scale() != get_scale())
```
I'd replace them with `is_zero`. Or was there a reason behind writing those things in this way?

**Comment by Expander** [comment]
Thanks for catching this! I'd prefer to use `is_zero`. Please feel free to fix it. :)

**Comment by wkotlarski** [comment]
BTW, `is_zero` function is defined many times though out the code. In
- `src/threshold_loop_functions.cpp`
- `src/numerics.cpp`
- `src/pmns.cpp`
- `src/ckm.cpp`
- `src/numerics2.hpp`

Should we put it just in one place?

**Comment by pathron** [comment]
Thanks Wojtek. I like both proposals.    Can we just include src/numerics2.hpp in the other files?

**Comment by Expander** [comment]
> BTW, `is_zero` function is defined many times though out the code. In
> 
>     * `src/threshold_loop_functions.cpp`
> 
>     * `src/numerics.cpp`
> 
>     * `src/pmns.cpp`
> 
>     * `src/ckm.cpp`
> 
>     * `src/numerics2.hpp`
> 
> 
> Should we put it just in one place?

Please leave it as is. Although the (trivial) `is_zero` function is replicated, this allows for a decoupling of the modules. I.e. since the function is so trivial, the decoupling is worth it, IMO.

**Comment by wkotlarski** [comment]
@Expander, maybe I'm wrong, but if the main `is_zero` is defined in `src/numerics2.hpp` and is required only by `.cpp` files than doesn't it mean there is no coupling at all?

**Comment by Expander** [comment]
You are right, the `.cpp` compilation modules are not coupled. What I mean is the coupling
~~~
src/threshold_loop_functions.cpp  ->  src/numerics2.hpp
src/numerics.cpp                  ->  src/numerics2.hpp
...
~~~
For example `src/threshold_loop_functions.cpp` would include `numerics2.hpp`, which would include
~~~
#include <array>
#include <cmath>
#include <complex>
#include <limits>
#include <cstddef>
#include <cstdlib>
#include <type_traits>
~~~
Actually, only `<limits>` which would not be necessary, but a ton of other stuff would be included. I.e. one would unnecessarily increase the compile time and coupling to a header file, which is not necessary.
