### ISSUE TITLE
models subdirectories in SARAH 4.14.4

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#290]
This works in 4.14.3
```mathematica
Start["LRmodels", "LRLR"]
```
but not in 4.14.4. What does work is this
```mathematica
Start["LRmodels/LRLR"]
```

**Comment by Expander** [comment]
Did the interface of the `Start[]` function change? If so, we may report a bug to Mark and Werner.

**Comment by Expander** [comment]
I've filed a bug report in the SARAH forum:
http://wernersarah.de/sarah_forum/viewtopic.php?f=12&t=687&sid=3bef7bd396cd470ef5a6f739d8213252

**Comment by wkotlarski** [comment]
The MSSMCPV also doesn't work but for a completely different reason. First, there's the warning
```
Converting self energies ...
[..................................................] 45/45

Solve::svars: Equations may not give solutions for all "solve" variables.
```
and then
```
Error: eta cannot be set in the constraint,
 
>    because it is neither a model nor an input parameter!
Error: The code generation failed!
```
This warning doesn't happen in 4.14.3.

**Comment by wkotlarski** [comment]
Mark solved it in next SARAH version.
