### ISSUE TITLE
Precision of diagonalization

### ISSUE THREAD

**Issue by uukhas** [FlexibleSUSY/FlexibleSUSY#291]
**Problem:** different results for higgs mixing matrix between `FlexibleSUSY` and `Mathematica`.
**How to reproduce:**
Let us `./configure` `MRSSM2` with default setup in order to see numerical diagonalization of `hh`.
After running `make` let us change a bit `get_mass_matrix_hh()` and `calculate_Mhh()` inside `models/MRSSM2/MRSSM2_mass_eigenstates.cpp` by adding `std::cout << mass_matrix_hh << "\n\n";` to the first function (before the last line) and by adding `std::cout << "ZH \n" << ZH << "\n\n";` to the last one. So we have now:
```Cpp
Eigen::Matrix<double,4,4> CLASSNAME::get_mass_matrix_hh() const
{
  ...
   Symmetrize(mass_matrix_hh);
   std::cout << mass_matrix_hh << "\n\n";
  ...
}
...
void CLASSNAME::calculate_Mhh()
{
  ...
   normalize_to_interval(ZH);
   std::cout << "ZH \n" << ZH << "\n\n";
 ...
}
```
Now run `make` again. We can see now right before the slha output numerical values of higgs mass matrix and matrix with eigenvectors. Now run the spectrum generator with attached lh file [LesHouches.in.MRSSM2](https://github.com/FlexibleSUSY/FlexibleSUSY/files/5715764/LesHouches.in.MRSSM2.txt).

We get:
```
    15847.3    -601.335    -637.332        5042
   -601.335     8155.52     47111.5     -201065
   -637.332     47111.5 2.18284e+06    -220.583
       5042     -201065    -220.583 7.57721e+06
```
for a higgs matrix (`Mhh`) and 
```
    0.032244     0.998896   -0.0215644    0.0264904
    -0.99948     0.032201 -0.000993872    0.0015227
 -0.00029792    0.0215704     0.999767  0.000845315
 0.000668237   -0.0265377 -0.000272452     0.999648
```
for a rotation (`ZH`)  one.
Let us look at the multiplication:
```mathematica
ZH.Mhh.Inverse[ZH] ->
{{1786.88, -0.00100501, -0.00629584, 0.295369}, 
 {-0.000810282, 15858.4, -0.000273787, 0.0171786}, 
 {-0.000586669, -0.000849014, 2.18386*10^6, -0.00352458},
 {-0.424028, -0.019123, -0.00916724, 7.58255*10^6}}
```
which looks more or less OK, because off-diagonal elements are much smaller then diagonal ones, which should be satisfactory.

But let us calculate `ZH` using Mathematica and `Mhh` matrix above:
```Mathematica
ZHnew = Reverse@Eigenvectors@Mhh 
->
{{-0.0322439, -0.998896, 0.0215644, -0.0264904}, 
 {0.99948, -0.0322009,   0.00099387, -0.0015227},
 {-0.00029792, 0.0215704, 0.999767,  0.000845316},
 {0.000668237, -0.0265377, -0.000272452, 0.999648}} 
```
as you can see, the only difference comes from first two rows by the **sign**. What is the result of explicit multiplication? It is the following
```Mathematica
ZHnew.Mhh.Inverse[ZHnew] ->
{{1786.88, 1.21538*10^-11, -1.42933*10^-10,  8.0469*10^-11},
 {1.2167*10^-11, 15858.4, -5.15525*10^-11,  3.61666*10^-12},
 {9.52546*10^-10, -2.81162*10^-11,  2.18386*10^6, -4.82032*10^-11}, 
 {2.91038*10^-11, 1.81899*10^-12, 2.00089*10^-11, 7.58255*10^6}}
```
where we can see that off-diagonal elements are much order below the ones of `FlexibleSUSY`.
**My Question:** is this satisfactory?
My concerns rise because of the following. Some higgs-interaction vertices in `MRSSM` have `ZH[i,2]*v + ZH[i,4]*mT` (`v` is vev, `mT` is the mass of T-field). `mT` should be heavy and the form of mentioned vertex can make contribution from small mixing values rather important. Also, during the calculation of observables we usually need to sum over all higgses. It means, that the form of mixing matrix here gives different sign of the whole vertex, than the one of `Mathematica` calculation. This seems to be weird for me at the first glance. 

Can you please say whether there is some option to make diagonalization more precise or I am missing something here (or something else)?

**Comment by Expander** [comment]
Dear @uukhas , many thanks for investigating!

I see your concerns. At first glance, it looks like a numerical instability. However, the sign difference looks a bit odd (but maybe it is not). Just for curiosity, would be the output, if you take `ZH` from FS and you multiply the first two rows by `-1`? Would you get the same as above? I'm just wondering if the sign cures the instability in some way.

The other strange thing is: By default Mathematica uses the machine precision of the underlying system to represent floating point numbers. So it is a bit surprising to me that the results for `ZH.Mhh.Inverse[ZH]` are so different.

I have another suggestion: Would you mind re-calculating the two terms:

* `ZH.Mhh.Inverse[ZH]`
* `ZHnew.Mhh.Inverse[ZHnew]`

but multiply each matrix element by some arbitrary symbol? The matrix product would then depend on this symbol. By replacing the these symbols by 1, step-by-step, one would find out where the numerical instability comes from, i.e. which terms do cancel such that a large error appears. (I'd call this trick the "Dominik trick", has he has suggested it to me once.)

If we wind that this is indeed a numerical instability which comes from the `Eigen` library, we'd have the following options:

* we try another (updated) version of Eigen
* we try another diagonalization algorithm from Eigen (if there is a suitable one)
* we try to find out the deeper reason for the instability and try to modify the input (`Mhh`) to avoid it
* we try to use another backend for the diagonalization routines from Eigen, like LAPACK or so (if this works)
* <your idea comes here>
* we formulate the physics in a slightly different way, for example using and EFT in your scenario, where you have a large mass splitting (this may be very challenging and may by far not be achievable easily)

**Comment by uukhas** [comment]
So, before going further into checks I have **increased** the cout **precision** by this (should have done this before):
```Cpp
typedef std::numeric_limits<double> dbl;
std::cout << std::setprecision(dbl::max_digits10);
```
Also, I was a little bit confused before. We have **rows** being equal to **eigenvectors** inside mixing matrix, which means, that the multiplication of any eigenvector (row) by -1 in principle is OK and physically equal to the different definition of higgs field, corresponding to this row.

The result is that for increased cout precision the results of `FlexibleSUSY` and `Mathematica` is of the same order for off-diagonal elements (`e-11`) and the values are the same (up to the factor +-2 or less, which is much more satisfactory, than before). 

I would say, that this issue should be treated as solved, because it was mainly caused by my wrong memories about `FS` eigenvectors conventions and usual missing of correct numerical input for first comparisons.

**Comment by Expander** [comment]
Ah, perfect, so there is no issue. No worries. :)
