### ISSUE TITLE
failing macOS tests

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#294]
@Expander, do you understand why macOS tests on travis fail?

**Comment by Expander** [comment]
Yes, travis-ci fails with MacOS due to a problem with TSIL. I'm working on it and have already prepared a patch.

BTW, we should probably remove travis-ci and only use github-actions.

**Comment by Expander** [comment]
The tests on travis-ci on MacOS now pass.

**Comment by wkotlarski** [comment]
Thanks a lot. I appreciate this. I know you're busy. I'll try to get your tests running on github.
