### ISSUE TITLE
more verbose message when a model has wrong name

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#31]
When a model name contains disallowed characters, e.g. '-', we print the following message: "Error: invalid model name". This is correct, but I'm afraid that the user might not figure out what to do with it. Maybe something like "Disallowed character in model name" would be better. We might be even more explicit and say exactly what is wrong. I could modify the appropriate function in createmodel script to do that.

**Comment by Expander** [comment]
Hi Wojciech,

I like your suggestion! Please feel free to modify the function to give a better error message. I'm looking forward to your pull request. :)

Best,
Alex

**Comment by pathron** [comment]
Hi Wojciech,

Good idea!  
> Maybe something like "Disallowed character in model name" would be better. We might be even more explicit and say exactly what is wrong. I could modify the appropriate function in createmodel script to do that.
> 

Being explicit and stating the offending character would be perfect, if it’s easy to do. Or you could just say "Disallowed character in model name, allowed characters in model names are...”

Cheers,
Peter

**Comment by wkotlarski** [comment]
Can you review commit d2d006f71c335ced79a44673d96596fcf6b2d2ea? It seems to do the trick. It's slighly longish because I wanted the formating to be nice. It should print something along the lines of
```
Error: invalid model name 7SMno-G@U-T. Model name must start with a letter. Disallowed character(s) in model name: - @.
```

**Comment by Expander** [comment]
That looks very nice! One comment, though: Would you mind using `printf` instead of `echo`? It is more portable, see https://unix.stackexchange.com/questions/65803/why-is-printf-better-than-echo .

**Comment by Expander** [comment]
Great, thanks! Would you mind creating a pull request for these three commits?
