### ISSUE TITLE
gm2calc problem

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#310]
I've added GM2Calc to the image but there is problem with linking
```
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /GM2Calc-clang++/lib64/libgm2calc.a(gm2_ffunctions.cpp.o): relocation R_X86_64_32 against symbol `_ZSt4cerr@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
```
Is there are reason `-fPIC` is not added by default by cmake? Should I add it manually?

**Comment by Expander** [comment]
Please compile with `-DCMAKE_POSITION_INDEPENDENT_CODE=ON` .

I'd not add this by default to GM2Calc's `CMakeLists.txt` file, because we should let the user decide. Also, this interferes with the creation of the conan GM2Calc package, where conan controls if `-fPIC` should be used or not.

**Comment by wkotlarski** [comment]
Thanks a lot for a quick reply :heart: Closing.
