### ISSUE TITLE
broken tests

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#311]
#308 broke tests. Sorry, I didn't notice it before I ok'ed the merge.
```
test/test_MSSM_stable_ewsb_failure.sh                              FAILED
```
```
Error: point has not converged, because
   SPINFO[4] contains "no convergence"

Test result: FAIL
```

**Comment by Expander** [comment]
Ok, I'll have a look

**Comment by Expander** [comment]
I can't reproduce this failure on my machine with the setup
~~~
./configure --with-models=MSSM --with-optional-modules=test
make
test/test_MSSM_stable_ewsb_failure.sh
~~~
Which setup is used that fails the test?

**Comment by wkotlarski** [comment]
I also don't get this error on my machine. Not sure how to debug it as logs don't contain anything else.

**Comment by wkotlarski** [comment]
Also, this change does give a relative difference for all widths of 1e-10? Should this change be neutral for all cases where we don't run QedQcd model?

**Comment by pathron** [comment]
Where are you seeing the error, its from the automated checks via the CI?  Sorry I am crap at reading these so its probably just me and I missing something / looking in the wring place, but I see a clang build error reported, but not the one you pasted.

**Comment by wkotlarski** [comment]
[here](https://github.com/FlexibleSUSY/FlexibleSUSY/runs/2140826848?check_suite_focus=true)

**Comment by pathron** [comment]
Thanks! Sorry I am was staring at that and somehow missing it.   .

**Comment by wkotlarski** [comment]
If you want to learn why a given test failed you have to download logs ([those ones in this particular case](https://github.com/FlexibleSUSY/FlexibleSUSY/suites/2292707045/artifacts/48045508)) and find a corresponding test log.

**Comment by Expander** [comment]
> Also, this change does give a relative difference for all widths of 1e-10? Should this change be neutral for all cases where we don't run QedQcd model?

The change only affects cases, where you run the QedQcd object to a scale above pole Mt.

**Comment by Expander** [comment]
By looking at the verbose output on my machine, it seems that the EWSB solving outcome depends on the GSL. If the virtual machine uses a different GSL version, the code may behave differently.

**Comment by Expander** [comment]
I've found a possible reason for the difference: The initial guess for the running mt uses the running mt from QedQcd. This value has slightly changed in the fix.

This would mean, that the test is sensitive to the initial guess, which is bad. I'm wondering if we should remove the test.

**Comment by wkotlarski** [comment]
But this still doesn't explain why there is a difference if we don't run QedQcd above the scale of mZ, right?

**Comment by Expander** [comment]
Well, it is just the initial guess that is slightly different, because in the initial guess we read the running mt from the QedQcd object (we don't do this anywhere else if we don't run above mt).

**Comment by wkotlarski** [comment]
do you know if your commit made any shift to lets say alpha_s at mZ (I'm looking for a shift at the 1e-10 level)?

**Comment by Expander** [comment]
I've checked that the value of alpha_s in the QedQcd class does not change, as long as one does not run above Mt. However, the initial guess for the value of g3 in the BSM model may change, because of a slightly different initial value of mt(SM(5)). This may affect the rest of the calculation slightly.

**Comment by pathron** [comment]
If an initial value in a fixed point iteration is changed then all the final values at the end of the iteration can change by some by quantities less than the convergence criteria.   So I would expect small changes everywhere that depend on the QedQcd parameters, or I am misunderstanding what is going on?

By the way why does a test to do with EWSB  require QedQcd at all?   Can’t the parameters used there just be fixed to numbers without including the QedQcd object at all?

**Comment by Expander** [comment]
@pathron you are exactly right, this is what happens. After the iteration has stopped, the result is different by a small numerical value below the precision goal.

However, this test point is designed to not converge and fail due to no EWSB. The small difference in the initial guess now somehow changes the iteration a bit (in an unstable way). On the CI the iteration stops with "no convergence". On my machine it stops with "no ewsb".

The test requires QedQcd in the way every spectrum generator requires it in the low-energy matching. Fixing it to numbers does not work well, because the test simply uses a SLHA input file.

**Comment by Expander** [comment]
@wkotlarski For this test point I see the following change in g3(BSM):
~~~
w/o fix: g3 = 1.01199814E+00
w/  fix: g3 = 1.01199751E+00
~~~
Would such a small change in g3(BSM) lead to the change in the decays that you observe?

**Comment by wkotlarski** [comment]
I see discrepancies at the the level of 1e-10. So it kind of consistent.

**Comment by Expander** [comment]
Thanks for the confirmation!

**Comment by Expander** [comment]
I'd vote for removing this test if it is so brittle. What do you think?

**Comment by pathron** [comment]
I don't have a problem with removing it.  Regarding your comment, sorry I wasn't realising its just a test of a full FS run that test the error gets caught and put in the output slha file.   I was thinking of a more "unity" test, that fixes some inputs and just tests the error is thrown  but I don't see this as necessary.

**Comment by wkotlarski** [comment]
As you decide. I'll follow your advice. I'm ok with removing them.

**Comment by Expander** [comment]
Thanks for your comments! I've removed it.
