### ISSUE TITLE
add check that rotation matrices are unitary

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#312]
Can we add a check that after mass diagonalization rotation matrices are unitary? @vytautasdudenas has some point which breaks diagonalization routine.

**Comment by wkotlarski** [comment]
Related question: in `linalg2.cpp` template arguments are called `Real`. Is it just name or do we really assume the matrices are real? We want to diagonalize complex symmetric matrix. I wrote a standalone program and eigen doesn't have problem with this matrix:
```cpp
include <iostream>    
#include <Eigen/SVD>    
#include <complex>    
#include <iomanip>    
    
using namespace Eigen;    
using namespace std;    
int main()    
{    
    
   MatrixXcd m(4,4);    
   m <<     
      0. , 0., 0., std::complex<double>(-4.4299349683288838e-06,7.0893778912230837e-06),    
      0. , 0., 0., 4.1620179585196247e-05,    
      0. , 0., 0., 3.7871449517912927e-05,    
      std::complex<double>(-4.4299349683288838e-06,7.0893778912230837e-06), 4.1620179585196247e-05, 3.7871449517912927e-05, 90.229999999964136;    
   cout << "Here is the matrix m:" << endl << m << endl;    
    
   JacobiSVD<MatrixXcd> svd(m, ComputeThinU | ComputeThinV);    
   cout << "Its singular values are:" << endl << setprecision(17) << svd.singularValues() << endl;    
    
   cout << "Its left singular vectors are the columns of the thin U matrix:" << endl << svd.matrixU() << endl;    
   cout << "U unitarity:" << endl << svd.matrixU() * svd.matrixU().conjugate().transpose() << endl;    
   cout << "Its right singular vectors are the columns of the thin V matrix:" << endl << svd.matrixV() << endl;    
   cout << "V unitarity" << endl << svd.matrixV() * svd.matrixV().conjugate().transpose() << endl;    
    
   return 0;    
}    
```

**Comment by wkotlarski** [comment]
The statement is that matrix `m` once passed through `fs_diagonalize_symmetric` gives garbage.

**Comment by wkotlarski** [comment]
This dumb `m` is complex, symmetric but not hermitian. It can be diagonalized by Takagi's factorization as
```
A = V D V^T
```
Is it possible that we don't catch this case and try to diagonalize it as
```
A = V D V^\dagger
```

**Comment by Expander** [comment]
Jae-hyeon's naming convention for the template parameters is:
* `Real` = real number
* `Scalar` = real or complex number

If you want to diagonalize a complex symmetric matrix, the following routines should do that:
* `fs_diagonalize_symmetric`
* `fs_diagonalize_symmetric_errbd`

Can you please check the output of the `fs_diagonalize_symmetric_errbd` routine? The parameters `s_errbd` and `u_errbd` give you some error estimate for the eigenvalues and eigenvectors, respectively.

If I recall correctly, Jae-hyeon has implemented Takagi's method in `diagonalize_symmetric_errbd`, see the comment referring to [see Eq. (5) of https://doi.org/10.1016/j.amc.2014.01.170](https://doi.org/10.1016/j.amc.2014.01.170). So, this case should in principle be catched. The routines that start with `fs_` return the result in the FS/SARAH convention w.r.t. the order of the eigenvalues etc.

**Comment by Expander** [comment]
Could you please paste here the output of your example with plain Eigen and the result of one of the FS routines?

**Comment by wkotlarski** [comment]
Sorry, this is incredibly scruffy but I was able to feed Vytautas's matrix to `fs_diagonalize_symmetric_errbd`. 
My eigenvalues are
```
    90.230000000000032
3.5867999999999997e-11
1.5162968682548454e-27
3.9127454457541113e-28
```
FS
```
3.91275e-28
 1.5163e-27
 3.5868e-11
      90.23
```
So all is fine there. But here are checks of rotations from FS

`rot * rot.transpose().conjugate()`
```
(1,0) (-7.10999e-13,-1.91524e-11)  (4.54029e-09,-1.50436e-10)  (8.02324e-24,-1.64379e-24)
 (-7.10999e-13,1.91524e-11)                 (182.064,0)          (-172.412,43154.1) (-1.38966e-22,-1.29468e-21)
  (4.54029e-09,1.50436e-10)         (-172.412,-43154.1)             (1.02288e+07,0)  (-3.33585e-20,3.38813e-21)
  (8.02324e-24,1.64379e-24)  (-1.38966e-22,1.29468e-21) (-3.33585e-20,-3.38813e-21)                       (1,0)
```

`rot * rot.transpose()`
```
(-0.382593,-0.86394)          (-1.56762,2.48878)           (591.384,369.227) (-1.30653e-07,-8.16411e-08)
         (-1.56762,2.48878)          (-177.577,3.24929)           (938.361,42087.5)  (-1.48138e-07,2.35186e-07)
          (591.384,369.227)           (938.361,42087.5)       (9.97499e+06,-262280)   (5.58849e-05,3.48914e-05)
(-1.30653e-07,-8.16411e-08)  (-1.48138e-07,2.35186e-07)   (5.58849e-05,3.48914e-05)            (1,-7.71496e-15)
```

**Comment by Expander** [comment]
Can you please print the output of
~~~
rot.transpose() * rot

~~~
? This should be the convention, IIRC.

**Comment by Expander** [comment]
One question: Is this a scenario where SVD could also be used?

**Comment by Expander** [comment]
What is the output of `s_errbd` and `u_errbd` from the routine?

**Comment by wkotlarski** [comment]
```
rot.transpose() * rot =
(-77175.4,-157930)          (-463192,742511)          (522364,-853422)   (0.00302747,0.00188561)
         (-463192,742511)    (4.35706e+06,-3296.99)    (-4.98146e+06,46077.1) (-2.60073e-05,-0.0177574)
         (522364,-853422)    (-4.98146e+06,46077.1)     (5.69493e+06,-101051)    (0.000203108,0.020302)
  (0.00302747,0.00188561) (-2.60073e-05,-0.0177574)    (0.000203108,0.020302)           (1,1.60984e-13)
```

**Comment by wkotlarski** [comment]
```
s_errbd =  2.00351e-14
u_errbd = 
1 
1
0.000558578
2.22045e-16
```

**Comment by Expander** [comment]
Oh dear! `u_errbd` means that we have indeed a 100% error here. It has probably to do with the multiple vanishing eigenvalues.

**Comment by Expander** [comment]
Does plain Eigen give the same incorrect mixing matrix/eigenvectors?

**Comment by wkotlarski** [comment]
Originally I made a "mistake". While using eigen I did SVD and there everything works. But then I realized that we are actually diagonalizaing this matrix in FS without SVD. So I have to rewrite my program.

**Comment by wkotlarski** [comment]
Pure eigen example (based on `ComplexEigenSolver`):
```
rot = 
       (0.619781,-0.745787)     (-0.989144,0.000415533)        (0.0617032,0.133364) (-4.06143e-08,-8.32716e-08)
        (0.011206,0.023877)      (-0.0575561,0.0921952)        (0.400294,-0.612377)  (-2.44435e-07,3.91177e-07)
     (-0.0794259,-0.229498)       (-0.052372,0.0838912)          (0.36424,-0.55722)  (-2.22418e-07,3.55944e-07)
  (2.18578e-17,5.43788e-18)  (3.04071e-20,-2.44237e-19)  (-3.24014e-07,5.18047e-07)        (-0.529919,0.848048)

rot.inverse() * m * rot = 
   (-7.1653e-31,6.0417e-31)   (7.49188e-33,6.98303e-33) (-9.55908e-21,-2.35603e-20) (-1.56604e-14,-3.85517e-14)
  (3.00014e-32,9.01451e-31)  (5.01431e-33,-1.16783e-32) (-2.42083e-20,-6.48671e-21) (-3.85215e-14,-1.10118e-14)
(-1.16795e-22,-6.00893e-23) (-5.30999e-23,-5.38568e-22)   (-3.4754e-11,6.96121e-13)   (8.84081e-15,2.57428e-15)
(-8.12275e-16,-2.03163e-15) (-8.68809e-17,-8.46398e-16)   (4.65963e-16,5.70862e-15)        (90.23,-6.96121e-13)
```
The small eigenvalue is slightly different and with an opposite sign.

**Comment by wkotlarski** [comment]
I'm really confused about what are we exactly trying to do here. By spectral theorem the matrix is diagonalizable (related to diagonal matrix by a unitary transformation) if it's normal (A A* = A* A). The matrix from Vytautas is not normal.

**Comment by Expander** [comment]
:D  Could you please sketch the Lagrangian mass terms that shall be diagonalized? Is this similar to anything we know in the MSSM or another model?

**Comment by wkotlarski** [comment]
I don't know much about this models. It has a right handed neutrino with interaction
```
LagYukawan = -( - Yn1 H1.n.l - Yn2 H2.n.l + 1/2 Mm n.n )
```
The physical states are defined as
```
{{vL,conj[nR]}, {VL,Un}}
```
Maybe @vytautasdudenas  can comment on that.

**Comment by Expander** [comment]
IIRC, @vytautasdudenas also had a problem with the chirality of the external states in the self-energies in FS. (This issue is unresloved, I think, sorry.) So one first point could be to check that the SARAH model file is correct (if not done already) and that SARAH creates the correct expressions for the mass matrices and self-energies.

**Comment by wkotlarski** [comment]
But isn't the problem kind of model independent? There is an example of a complex symmetric matrix that when passed to `fs_diagonalize_symmetric` gives a non-unitary rotation?

**Comment by Expander** [comment]
You are right, this is a numerical problem.
I was just suspecting that there may be a problem also with the spinor definitions in the SARAH model, but maybe this is not the case.

**Comment by vytautasdudenas** [comment]
I think the problem is in taking a square root of a matrix, when doing Takagi factorization from https://doi.org/10.1016/j.amc.2014.01.170. I got the same problem, when modifying initial Wojciech cpp code to have = UnT mdiag Un as is done that 
 paper. The code: 

`#include <iostream>
#include <Eigen/SVD>
#include <complex>
#include <iomanip>
#include <unsupported/Eigen/MatrixFunctions>


using namespace Eigen;
using namespace std;
int main()
{

   MatrixXcd m(4,4);
   m << 
      0. , 0., 0., std::complex<double>(-4.4299349683288838e-06,7.0893778912230837e-06),
      0. , 0., 0., 4.1620179585196247e-05,
      0. , 0., 0., 3.7871449517912927e-05,
      std::complex<double>(-4.4299349683288838e-06,7.0893778912230837e-06), 4.1620179585196247e-05, 3.7871449517912927e-05, 90.229999999964136;
   cout << "Here is the matrix m:" << endl << m << endl;

   JacobiSVD<MatrixXcd> svd(m, ComputeThinU | ComputeThinV);
   cout << "Its singular values are:" << endl << setprecision(17) << svd.singularValues() << endl;


   MatrixXcd Z(4,4);
   Z << (svd.matrixU().transpose().conjugate()) *(svd.matrixV().conjugate()) ;
   MatrixXcd Zsqrt(4,4);
   Zsqrt << Z.sqrt() ;
   MatrixXcd Un(4,4);
   Un << svd.matrixU()* Zsqrt;
   cout << "UnconjT m Unconj" << endl << Un.conjugate().transpose()* m *Un.conjugate() << endl;
   cout << " UnconjT * Un" << endl << Un.conjugate().transpose() *Un << endl;


   return 0;
}`

It returns: 
`UnconjT m Unconj
      (90.230000000000089,2.0691821543956274e-29) (-1.6051274350468991e-19,-1.7672495411513722e-17) (-1.0143219543370247e-19,-5.2079680141226522e-18) (-1.7410594466183153e-18,-4.1708792566746013e-22)
(-1.6046162125822028e-19,-1.7651611086493836e-17)  (3.5857022204021248e-11,-6.3521838798198909e-13) (-4.8164251698413499e-15,-2.8014110615147341e-13)  (4.0988219482816369e-27,-2.6210074092719549e-27)
 (-1.014718633196115e-19,-5.2060861712749378e-18) (-4.8164251698357151e-15,-2.8014110615147336e-13)  (-2.1886652353344819e-15,3.6485934037734212e-17) (-1.4176524305983272e-29,-3.0359320605118704e-29)
(-1.7414997395551901e-18,-4.1708792566745689e-22)  (4.0572209208244848e-27,-2.1413668109817523e-27) (-1.6713202651723315e-29,-3.1706401809709588e-29)   (3.3593346595717753e-38,6.1157278631379961e-42)
 UnconjT * Un
                           (1.0000000000000009,0) (-3.0605682664462024e-23,-5.2939559203393771e-23)  (-1.075334796318936e-22,-5.2939559203393771e-23)   (1.3234889800848443e-23,4.6224972366797946e-24)
 (-3.0605682664462024e-23,5.2939559203393771e-23)                             (6.140630263725841,0)        (2.2671636237946231,0.0076096125624591877)   (5.9370910965306223e-16,3.8857805861880479e-16)
  (-1.075334796318936e-22,5.2939559203393771e-23)       (2.2671636237946231,-0.0076096125624591877)                           (0.99991182330776041,0)   (5.9847959921199845e-17,8.3266726846886741e-17)
 (1.3234889800848443e-23,-4.6224972366797946e-24)  (5.9370910965306223e-16,-3.8857805861880479e-16)  (5.9847959921199845e-17,-8.3266726846886741e-17)                            (1.0000000000000004,0)`

However, if you just change the matrix a little bit, say 44 element from 90... -> 91..., it gives near perfect results: 

`UnconjT m Unconj
      (91.229999999999606,3.3838783258086592e-29) (-4.8183284283307707e-21,-5.7123901962830015e-18)  (5.0934333933225855e-18,-7.1577200048677012e-20) (-1.6482195596283986e-18,-4.4375268255604614e-19)
(-4.8183284283308956e-21,-5.7160261064107932e-18)   (3.5474839855310902e-11,1.5424569989945101e-27)  (-4.4933517161275667e-27,3.2311742687017984e-27)   (1.3167173990634439e-27,8.4651134592675797e-27)
 (5.0923620788938459e-18,-7.1468404924592749e-20)   (-4.3887763140099092e-27,2.780816393787694e-27)  (2.8408136921061219e-37,-7.9795195840760195e-39) (-9.2226054201329791e-38,-2.3496531189282772e-38)
(-1.6483261153571832e-18,-4.4384526436134033e-19)   (9.7913500939052307e-28,9.1532832504620277e-27) (-9.2218182949657857e-38,-2.3471841350290496e-38)   (2.7578764167764147e-38,1.6033044847434128e-38)
 UnconjT * Un
                                            (1,0)  (-5.2333990498966941e-23,5.2939559203393771e-23)  (-2.1175823681357508e-22,-2.481541837659083e-24)                                             (0,0)
(-5.2333990498966941e-23,-5.2939559203393771e-23)                            (1.0000000000000002,0) (-5.5684623578855508e-16,-5.5511151231257827e-16) (-4.8572257327350599e-17,-5.8286708792820718e-16)
  (-2.1175823681357508e-22,2.481541837659083e-24)  (-5.5684623578855508e-16,5.5511151231257827e-16)                           (0.99999999999999845,0)  (4.0245584642661925e-16,-8.3960616237277463e-16)
                                            (0,0)  (-4.8572257327350599e-17,5.8286708792820718e-16)   (4.0245584642661925e-16,8.3960616237277463e-16)                           (0.99999999999999845,0)
`

**Comment by vytautasdudenas** [comment]
@wkotlarski, it doesn't have to be normal, just symmetric. It is diagonalized as Un^T mdiag Un = M, where mdiag consists of singular values, and Un^T !=Un^-1.  If Alex is right, and FS uses the method described in  https://doi.org/10.1016/j.amc.2014.01.170., then you can first get U, V  and mdiag from SVD, and then construct 
Un = U * Z^(1/2), 
where 
Z = U^\dagger V* .
In the example of my previous comment, I showed that this taking square root of a matrix from eigen's <unsupported/Eigen/MatrixFunctions> might be a problem, as it sometimes gives non-unitary Z^(1/2), which in turn gives non-unitary Un. I don't know though, if this is exactly how FS does this, as the exact numbers in FS seems to be different for Un.ConjT* Un, than in this cpp example.

**Comment by Expander** [comment]
@vytautasdudenas thanks for the detailed comment! Your example suggests, that in your example code the call `Z.sqrt()` sometimes returns incorrect numbers, probably due to an instability in its implementation, right?

FS does exactly what you're saying (`src/linalg2.hpp`):
~~~cpp
template<class Real, int N>
void diagonalize_symmetric_errbd
(const Eigen::Matrix<std::complex<Real>, N, N>& m,
 Eigen::Array<Real, N, 1>& s,
 Eigen::Matrix<std::complex<Real>, N, N> *u = 0,
 Real *s_errbd = 0,
 Eigen::Array<Real, N, 1> *u_errbd = 0)
{
    if (!u) {
	svd_errbd(m, s, u, u, s_errbd, u_errbd);
	return;
    }
    Eigen::Matrix<std::complex<Real>, N, N> vh;
    svd_errbd(m, s, u, &vh, s_errbd, u_errbd);
    // see Eq. (5) of https://doi.org/10.1016/j.amc.2014.01.170
    *u *= (u->adjoint() * vh.transpose()).sqrt().eval();
}
~~~
I.e. it uses the `.sqrt()` method, which (according to your example) is unstable here.

It sounds to me that we should file a bug report at the Eigen bug tracker with your example. What do you think?

**Comment by vytautasdudenas** [comment]
I think so too, yes.

**Comment by vytautasdudenas** [comment]
OK, sorry, I am a bit confused. The Z-matrix, that I get with this example, if you neglect O(10^-16) elements, is basically diag(1,-1,-1,1):
``` Z
     (1.0000000000000004,-7.8886090522101181e-31) (-5.2939559203393771e-23,-8.2718061255302767e-25)                       (-2.1175823681357508e-22,0)                       (-2.6469779601696886e-23,0)
                       (0,8.2718061255302767e-25)      (-1.0000000000000002,1.7347234759768071e-18)                       (0,-1.7347234759768071e-18)  (-1.3877787807814457e-16,1.3877787807814457e-17)
 (-2.1175823681357508e-22,8.2718061255302767e-25)                       (-2.7755575615628914e-16,0)     (-1.0000000000000002,-1.7347234759768071e-18)   (1.1102230246251565e-16,6.9388939039072284e-18)
                       (6.6174449004242214e-23,0)                       (-5.5511151231257827e-17,0)   (2.7755575615628914e-17,6.9388939039072284e-18)                            (1.0000000000000002,0)
```

The square root of it, however, have significant off-diagonal terms:  
``` Zsqrt
     (1.0000000000000002,-3.9443045261050582e-31) (-2.4970219418783557e-23,-2.1400364535249398e-22) (-1.0514820755423219e-22,-1.0587202121643911e-22) (-1.3234889800848441e-23,-2.3725157904350058e-38)
                                            (0,0)      (-0.0088559537566600365,0.99988617698020199)  (-0.0078118010490741806,-6.5108417209846153e-05)  (-1.2778371809946391e-16,1.2097972777886129e-16)
                                            (0,0)         (0.020282739311665372,-2.267237984724769)       (0.008855953756660033,-0.99988617698020188)    (-7.9696772985455e-17,-2.4737867260339628e-16)
                                            (0,0)  (1.4676384445835139e-17,-2.9683585789002261e-16) (-1.6818325345318266e-16,-1.0848719016788036e-16)                        (1,3.2027354498051594e-19)
```

and is not unitary, but .sqrt() does its job in the sense that Zsqrt * Zsqrt gives me again: 

``` Zsqrt ^2 
     (1.0000000000000004,-7.8886090522101181e-31) (-5.2939559203393724e-23,-8.2718061255297671e-25)  (-2.1175823681357508e-22,1.3190759514898464e-38)  (-2.6469779601696874e-23,1.1319819000133995e-38)
                                            (0,0)     (-1.0000000000000002,-6.9388939039071883e-18)   (2.7105054312172229e-20,-8.673617379884101e-19) (-2.4701156000104121e-16,-5.9231745617228102e-18)
                                            (0,0)  (-7.4600520985351149e-32,1.3877787807814475e-17)     (-0.99999999999999989,3.4694469519536643e-18)  (-5.6055048778006235e-17,1.2228815475473116e-16)
                                            (0,0)    (6.1970986709104616e-17,9.957866390302642e-17)  (-2.7828149390498364e-16,6.1034029730104533e-17)                        (1,6.4054708996112183e-19)
```
which is again, unitary. Square root of a unitary matrix should be unitary, right?  What is going on here...

**Comment by wkotlarski** [comment]
So Is the origin of the problem the routine that calculates sqrt of a matrix? If yes this might be a problem because it comes from an [unsupported](https://eigen.tuxfamily.org/dox/unsupported/group__MatrixFunctions__Module.html#title9) module. According to the webpage
```
These modules are contributions from various users. They are provided "as is", without any support.
```

**Comment by wkotlarski** [comment]
There are two ways to get sqrt of a matrix in eigen. One is to use a build in function `.sqrt`. The other one is to encode your own and use `.matrixFunction` method. This second way does give a correct result
```cpp
#include <iostream>    
#include <complex>    
#include <unsupported/Eigen/MatrixFunctions>    
#include <cmath>    
    
using namespace Eigen;    
using namespace std;    
    
std::complex<double> sqrtfn(std::complex<double> x, int n)    
{    
  return std::pow(x, 1/2. - n)*tgamma(1.5)/tgamma(1.5-n);    
}    
    
int main()    
{    
    
   MatrixXcd m(4,4);    
   m <<    
      std::complex<double>(1.0000000000000004,-7.8886090522101181e-31), std::complex<double>(-5.2939559203393771e-23,-8.2718061255302767e-25), std::complex<double>(-2.1175823681357508e-22,0), std::complex<double>(-2.6469779601696886e-23,0),    
      std::complex<double>(0,8.2718061255302767e-25), std::complex<double>(-1.0000000000000002,1.7347234759768071e-18), std::complex<double>(0,-1.7347234759768071e-18), std::complex<double>(-1.3877787807814457e-16,1.3877787807814457e-17),    
      std::complex<double>(-2.1175823681357508e-22,8.2718061255302767e-25), std::complex<double>(-2.7755575615628914e-16,0), std::complex<double>(-1.0000000000000002,-1.7347234759768071e-18), std::complex<double>(1.1102230246251565e-16,6.9388939039072284e-18),
      std::complex<double>(6.6174449004242214e-23,0), std::complex<double>(-5.5511151231257827e-17,0), std::complex<double>(2.7755575615628914e-17,6.9388939039072284e-18), std::complex<double>(1.0000000000000002,0);    
    
   std::cout << m.sqrt() << std::endl;    
   std::cout << m.matrixFunction(sqrtfn) << std::endl;    
   return 0;    
}    
```
Giving from `.sqrt`
```
            (1,-3.9443e-31) (-2.49702e-23,-2.14004e-22) (-1.05148e-22,-1.05872e-22) (-1.32349e-23,-2.37252e-38)
                      (0,0)      (-0.00885595,0.999886)   (-0.0078118,-6.51084e-05)   (-1.27784e-16,1.2098e-16)
                      (0,0)        (0.0202827,-2.26724)      (0.00885595,-0.999886) (-7.96968e-17,-2.47379e-16)
                      (0,0)  (1.46764e-17,-2.96836e-16) (-1.68183e-16,-1.08487e-16)             (1,3.20274e-19)
```
and from handwritten
```
           (1,-3.9443e-31) (-2.68834e-23,2.60562e-23) (-1.05879e-22,1.05879e-22) (-1.32349e-23,2.93874e-39)
                     (0,0)            (6.12079e-17,1)  (8.67362e-19,-3.2377e-17) (-1.26801e-16,1.20874e-16)
                     (0,0) (-1.30104e-18,9.34853e-17)             (6.2451e-17,1)  (-5.16299e-17,4.1847e-18)
                     (0,0) (1.86962e-17,-4.50374e-17) (-1.63634e-16,1.13594e-16)            (1,1.24129e-32)
```

**Comment by Expander** [comment]
@wkotlarski Wow! Where did you get the inspiration for `sqrtfn` from?

**Comment by wkotlarski** [comment]
It's because my life is very sad 😞 A more important question is what do we do now. For this case it works fine. But I'm reluctant to suggest to change sqrt to handwritten sqrt in FS. Can we add a check that the rotation matrix computed by `fs_diagonalize_symmetric` is unitary? Because currently there's a danger of silently producing garbage. This would be a good first step.

**Comment by Expander** [comment]
We have `--enable-debug` and `--enable-verbose` which sets debug/verbose flags that could be used to add the ckeck. In fact, we already add error checks (search for `CHECK_EIGENVALUE_ERROR`) for eigen values. We may simply extend this check.

Before we replace `.sqrt()` by your (very cool) hand-written one, we'd have to properly test it, of course. (Does anyone know how Eigen implements it, if there is such a cool Wojtex-like implementation?)

**Comment by wkotlarski** [comment]
It's in `eigen3/unsupported/Eigen/src/MatrixFunctions/MatrixSquareRoot.h`. It seems to be base on Shur's decomposition
```cpp
template <typename MatrixType>    
struct matrix_sqrt_compute<MatrixType, 1>    
{    
  typedef typename MatrixType::PlainObject PlainType;    
  template <typename ResultType>    
  static void run(const MatrixType &arg, ResultType &result)    
  {    
    eigen_assert(arg.rows() == arg.cols());    
    
    // Compute Schur decomposition of arg    
    const ComplexSchur<PlainType> schurOfA(arg);    
    const PlainType& T = schurOfA.matrixT();    
    const PlainType& U = schurOfA.matrixU();    
        
    // Compute square root of T    
    PlainType sqrtT;    
    matrix_sqrt_triangular(T, sqrtT);    
        
    // Compute square root of arg    
    result = U * (sqrtT.template triangularView<Upper>() * U.adjoint());    
  }    
}; 
```

**Comment by wkotlarski** [comment]
from [here](https://eigen.tuxfamily.org/dox/unsupported/group__MatrixFunctions__Module.html#title12):
The computation is the same as in the real case, except that the complex Schur decomposition is used to reduce the matrix to a triangular matrix. The theoretical cost is the same. Details are in: Åke Björck and Sven Hammarling, "A Schur method for the square root of a matrix", Linear Algebra Appl., 52/53:127–140, 1983.

**Comment by wkotlarski** [comment]
@vytautasdudenas, has you checked that with my version you're getting the result you expect from your calculation?

**Comment by vytautasdudenas** [comment]
Hi @wkotlarski , the issue with sqrt() is that it sometimes does not give unitary matrix out of unitary matrix, even though, squaring the result gives back the initial input matrix. On the other hand,  matrixFunction(sqrtfn) gives unitary matrix, where sqrt() does not. I am confused about it too (see my previous comment about sqrt of almost diagonal matrix). The paper that the expression is taken from ( https://doi.org/10.1016/j.amc.2014.01.170 ) seems to assume that Zsqrt is unitary.  So the expression for Takagi decomposition that is written in FS works only if sqrt function gives unitary matrix...

**Comment by Expander** [comment]
Thanks for the explanation! It seems to me that one could argue that the issue is about the guarantees that are given by the square-root function used:

* `matrixFunction(sqrtfn)` guarantees to return a matrix `A` with `A*A == M` and `A` is unitary if `M` is unitary.
* `A = M.sqrt()` guarantees to return a matrix `A` with `A*A == M`.

Could that be a correct argumentation?

**Comment by wkotlarski** [comment]
What you're talking about @vytautasdudenas, is physics. I was now thinking about math :) Is it possible that mathematically a square of a matrix is not uniquely defined (clearly it's not, as we have an example)? Than we should not file a bug report with Eigen as it does exactly what it promises. Given a matrix `M` it gives `A` such that `A*A == M`. Now, if @Expander is right with his summary, then we should replace the use of `sqrt()` with `matrixFunction(sqrtfn)` as the construction we use assumes that the output will be unitary, right?
