### ISSUE TITLE
massless SM fermions in the LRLR model

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#313]
All SM fermions are massless
```
         1     0.00000000E+00   # Fd(1)
         3     0.00000000E+00   # Fd(2)
         5     0.00000000E+00   # Fd(3)
   6000001     0.00000000E+00   # Fd(4)
   6000003     0.00000000E+00   # Fd(5)
   6000005     0.00000000E+00   # Fd(6)
         2     0.00000000E+00   # Fu(1)
         4     0.00000000E+00   # Fu(2)
         6     0.00000000E+00   # Fu(3)
   6000002     0.00000000E+00   # Fu(4)
   6000004     0.00000000E+00   # Fu(5)
   6000006     0.00000000E+00   # Fu(6)
        11     0.00000000E+00   # Fe(1)
        13     0.00000000E+00   # Fe(2)
        15     0.00000000E+00   # Fe(3)
   6000011     0.00000000E+00   # Fe(4)
   6000013     0.00000000E+00   # Fe(5)
   6000015     0.00000000E+00   # Fe(6)
        12     0.00000000E+00   # Fv(1)
        14     0.00000000E+00   # Fv(2)
        16     0.00000000E+00   # Fv(3)
   6000012     0.00000000E+00   # Fv(4)
   6000014     0.00000000E+00   # Fv(5)
   6000016     0.00000000E+00   # Fv(6)
```
Is this how it should be? Is the model physical at all?

**Comment by Expander** [comment]
That's normal, there is nothing to see here ...  :D

**Comment by Expander** [comment]
I don't know anything about this model, it may be a fantasy thing or FS cannot properly deal with it.

**Comment by wkotlarski** [comment]
I will disable decays in that model then. They can be generated but there's a test that runs all spectrum generators with default input card. And decays crash if SM fermions are massless.

**Comment by Expander** [comment]
Yes, please disable the decays for this model.

**Comment by wkotlarski** [comment]
Thanks, I'll do that. @pathron you want to comment on the origin of this model? If not I'll close the issue in 24h.

**Comment by pathron** [comment]
So I don’t know who created this model.  Left-Right models are important and interesting so it would be nice to have one.  

However actually looking at this one it references a 750 GeV diphoton paper, so was this from that project?   I don’t recall what we did with all those models,  originally they were in a downloadable pack, but they can’t all be in model_files list, so I am not sure why this is here.

**Comment by pathron** [comment]
Looking at the model a file and the LesHouches file it looks like there is areinput blocks for the fermion masses and they are just set to zero.   I can’t see what them being used in the model file but maybe I miss something and just setting the diagonal entries of the FDIN etc to the correct fermion masses will work?

**Comment by pathron** [comment]
I am fine with you anyway disabling decays for this model, since we are confused about it.

**Comment by Expander** [comment]
Ok, maybe we could also set the mass input parameters to some non-zero values to avoid the confusion.  :)

**Comment by wkotlarski** [comment]
But why are SM masses free parameters? Shouldn't they be always determined via the matching to the SM?

**Comment by Expander** [comment]
I have no idea, it is just how the SARAH/FS model files were invented to match the corresponding 750 GeV paper the model refers to. :)

**Comment by wkotlarski** [comment]
I put some numbers which give
```
         1     3.94974875E+00   # Fd(1)
         3     6.89804157E+00   # Fd(2)
         5     1.23530317E+01   # Fd(3)
   6000001     1.00783933E+02   # Fd(4)
   6000003     7.21936570E+02   # Fd(5)
   6000005     2.83685995E+03   # Fd(6)
         2     4.52745509E-02   # Fu(1)
         4     3.50281520E+00   # Fu(2)
         6     7.83512855E+00   # Fu(3)
   6000002     1.58898110E+02   # Fu(4)
   6000004     1.42169889E+03   # Fu(5)
   6000006     2.47487470E+05   # Fu(6)
        11     1.51422786E+01   # Fe(1)
        13     1.75137321E+01   # Fe(2)
        15     3.13346026E+01   # Fe(3)
   6000011     7.10863403E+01   # Fe(4)
   6000013     1.58928088E+02   # Fe(5)
   6000015     7.39973445E+02   # Fe(6)
        12     1.41421356E-03   # Fv(1)
        14     2.82842712E-03   # Fv(2)
        16     4.24264069E-03   # Fv(3)
   6000012     1.41421356E+02   # Fv(4)
   6000014     2.82842712E+02   # Fv(5)
   6000016     4.24264069E+02   # Fv(6)
```
I wouldn't want to spent time tuning this point...

**Comment by Expander** [comment]
That is very nice, many thanks! Yes, don't spend more time on this point.

**Comment by wkotlarski** [comment]
Thanks! I'll commit a fix.
