### ISSUE TITLE
odd semi random error

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#314]
There's an odd random error in `test_flexiblesusy-config.sh`
```
In file included from src/bvp_solver_problems_format_mathlink.hpp:22:0,
                 from test/SM/SM_librarylink.cpp:35:
src/mathlink_utils.hpp:22:10: fatal error: mathlink.h: No such file or directory
 #include <mathlink.h>
          ^~~~~~~~~~~~
compilation terminated.
==============
Result: FAILED
Error: build failed in directory test/SM
==============
```
I'm saying odd because during the same run the same test passed fine with clang but failed with gcc.

**Comment by Expander** [comment]
That is indeed very strange, as the test passes with gcc in the nighly test:
https://flexiblesusy.hepforge.org/test/FlexibleSUSY/test/test_flexiblesusy-config.sh.log

**Comment by Expander** [comment]
Could you please paste here the explicit compilation command (including all the `-I...` stuff) that leads to this error?

**Comment by wkotlarski** [comment]
This might be related #317. I've changed CI to save `config.*` files and call `make showbuild`. Lets see. Closing for now. Thanks!
