### ISSUE TITLE
where doesn ENABLE_TWO_SCALE_SOLVER come frome?

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#318]
Like in the title. There's a lot of
```
#ifdef ENABLE_TWO_SCALE_SOLVER
```
but I cannot find a place where it comes from.

**Comment by Expander** [comment]
It is determined in the `configure` script and defined/undefined in `config/config.h`.

**Comment by wkotlarski** [comment]
I'm sorry @Expander. I swear, I did grep for it. I just wasn't expecting it in the config dir.
