### ISSUE TITLE
auto package models on release

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#320]
We could use github to automatically create packaged models on a new release using syntax
```
on:
  release:
    types: [published]
```
Do you think it would be useful? If yes, can you tell me how you package those models?

**Comment by Expander** [comment]
That's a great idea! Some questions:
* Where would the generated tarballs be stored and can be downloaded?
* Can this new entry in the `.yml` file be tested? (Since I've never got these yaml entries right the first time, I'm worried that it may not work correctly if it is not tested.)

To generate the pre-generated model source codes I'm running (on the release commit):
~~~
./release/generate-models.sh --number-of-jobs=4 --directory=release/<version>
./release/generate-slha-output.sh --directory=release/<version>-slha
~~~
The results are stored in the `release/<version>` and `release/<version>-slha` sub-directories. The generated files are then uploaded by hand to hepforge and to https://github.com/FlexibleSUSY/FlexibleSUSY-generated and https://github.com/FlexibleSUSY/FlexibleSUSY-slha . All of this is also documented in the `doc/release` file, if you like to look it up.

**Comment by wkotlarski** [comment]
What I had in mind was to process them and commit them to [https://github.com/FlexibleSUSY/FlexibleSUSY-generated](https://github.com/FlexibleSUSY/FlexibleSUSY-generated) and [https://github.com/FlexibleSUSY/FlexibleSUSY-slha](https://github.com/FlexibleSUSY/FlexibleSUSY-slha). Side question: there are models which require himalaya but the script `generate-models.sh` doesn't have an option to specify it's location.

**Comment by Expander** [comment]
That's a good idea!

Yes, there is currently no for the `generate-models.sh` script to specify the location of the Himalaya libraries (also for TSIL). It must either be added, or we rely on the configure script to automatically find them (which will not always work).

**Comment by wkotlarski** [comment]
I'll set it up such that action will create a PR on FlexibleSUSY-generated and FlexibleSUSY-slha. Once we convince ourself that everything works we can drop the PR step.

**Comment by Expander** [comment]
If that would work, it would best! I just thought to test it one must actually create a release, which we probably don't want to do for testing.

**Comment by wkotlarski** [comment]
I have it working now. I only need now the himalaya configure options exposed.

**Comment by Expander** [comment]
I think it would best to name them according to the options in `configure`, i.e.:
~~~
--with-himalaya-libdir=
--with-himalaya-incdir=
~~~
Would you be ok with this?

Should we also add an option for the list of models to build? Maybe like so:
~~~
release/generate-models.sh --with-models=SM,CMSSM,MRSSM2
~~~

**Comment by wkotlarski** [comment]
Those himalaya options would be fine. Regarding models I was ok with them being hardcoded in `generate-models.sh`.

**Comment by Expander** [comment]
Ok, then I'll leave it as it is. I just noticed that you did remove the list of models. But I guess this was just for testing.

**Comment by wkotlarski** [comment]
Yes. I'll revert it before the merge.

**Comment by Expander** [comment]
I've adapted the `generate-models.sh` script. I've added the following options:
~~~
  --with-himalaya-libdir=   Path to search for Himalaya library
  --with-himalaya-incdir=   Path to search for Himalaya header
  --with-models=            Comma separated list of models to be generated
~~~
The default output directory for the tarballs is now `.`

**Comment by wkotlarski** [comment]
I think there's a problem because some models are named differently in SARAH and FS
```
Searching for THDMII-II model file ... no found in model_files/THDMII-II
Error: No FlexibleSUSY model file found in model_files/THDMII-II/
```

**Comment by Expander** [comment]
Ouch! Sorry, this is my mistake. I've just corrected the model names.

**Comment by wkotlarski** [comment]
BTW, why did you choose those models as default? Are they of special interest?

**Comment by wkotlarski** [comment]
I'm sorry, I'll also need options for TSIL.

**Comment by wkotlarski** [comment]
Also, once Decays are merged, do you want the generated code to include decays. Because if yes then I also need an option for loop libraries.

**Comment by Expander** [comment]
Well, I've selected the models just because of my own and Peter's interest. :) We may of course extend/adapt the list of default models.

**Comment by Expander** [comment]
Yes, decays should be included. I'll add an option for TSIL and the loop libraries.

**Comment by wkotlarski** [comment]
Thanks. I've added TSIL to the docker image. Another BTW, tsil is weird. Seems one cannot specify a C compiler.

**Comment by Expander** [comment]
For me the following works with TSIL:
~~~
make CC=clang
~~~

**Comment by Expander** [comment]
I've just extended the `generate-models.sh` to accept TSIL and the loop libraries.

**Comment by wkotlarski** [comment]
> For me the following works with TSIL:
> 
> ```
> make CC=clang
> ```

Funny. `make CC=clang` works, but `CC=clang make` doesn't. I always though it works both ways.

**Comment by Expander** [comment]
As far as I know the difference is:
* `make CC=clang` sets the `CC` variable inside the `Makefile`
* `CC=clang make` sets the `CC` shell environment variable. The `Makefile` may read it or not. For TSIL it seems not to do so.

**Comment by wkotlarski** [comment]
That's actually really interesting. You're a bash wizard :)

**Comment by Expander** [comment]
Once in a lifetime every programmer has to dwell down into this hell.  :)

**Comment by wkotlarski** [comment]
Everything seems to work now. Please check if those lines are ok
```
git commit --allow-empty -m "version $FS_TAG" && git tag v$FS_TAG    
git push origin    
git push origin v$FS_TA
```
In the end I plan to commit directly to master.

**Comment by Expander** [comment]
That looks perfect! :)
