### ISSUE TITLE
conan error

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#321]
```
/tmp/FlexibleSUSY % conan install . --build=missing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

ERROR: {"message":"Repo 'conan-hep' was not found"}. [Remote: conan-hep]
```

**Comment by Expander** [comment]
Yes, this a shame. BinTray shut his service down, so the `conan-hep` conan repo is no longer available. :(
I've already started to migrate our dependent packages to the official https://github.com/conan-io/conan-center-index .

Now there is already:
* TSIL https://github.com/conan-io/conan-center-index/tree/master/recipes/tsil
* GM2Calc https://github.com/conan-io/conan-center-index/tree/master/recipes/gm2calc

I'm currently migrating
* Himalaya https://github.com/conan-io/conan-center-index/pull/4681
* COLLIER https://github.com/conan-io/conan-center-index/pull/5375

However, for the packages that require a Fortran complere there is an issue with the gfortran dependency: https://github.com/conan-io/conan-center-index/issues/4696 So, Himalaya and COLLIER are currently on hold.

Anyway, for the moment we cannot use the `conan-hep` repository.

**Comment by Expander** [comment]
There are two workarounds that I can think of:

* A user installs Himalaya and COLLIER manually and passes the paths to `configure`.
* A user downloads the (preliminary) recipes for Himalaya https://github.com/Expander/conan-center-index/tree/himalaya and COLLIER https://github.com/Expander/conan-center-index/tree/collier locally and installs them.

Personally, I think the first option is a bit better, but not optimal.

**Comment by wkotlarski** [comment]
Should I change the tests to do option 1 or disable conan tests for now?

**Comment by Expander** [comment]
I'd say disabling the conan-style tests for now would be best. But only if there are tests that compensate for this, i.e. we still test properly. :)

**Comment by wkotlarski** [comment]
Not my area of expertise but [some](https://crystal-lang.org/2021/04/30/new-apt-and-rpm-repositories.html) projects are moving from bintray to OBS.

**Comment by Expander** [comment]
Thanks for the info, I'll have a look!

**Comment by Expander** [comment]
Here is a branch for LoopTools (not yet in the official conan center index):
https://github.com/Expander/conan-center-index/tree/looptools

**Comment by wkotlarski** [comment]
Have you seen [this](https://conan.io/center/tsil)?

**Comment by Expander** [comment]
Yes, I've put it there. :)

**Comment by wkotlarski** [comment]
Yeah, ok. That makes more sense. And I thought for a moment that S. P. Martin is into such a new technologies :)

**Comment by Expander** [comment]
I am still working on getting Himalaya, LoopTools and COLLIER into the official conan repository. However, due to the lack of FORTRAN support, this is probably not going to happen very soon.

So, for now we should remove Himalaya, LoopTools and COLLIER from our `conanfile.txt`. Then at least boost, eigen, gm2calc and tsil can be installed via conan.
