### ISSUE TITLE
packaging models without decays

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#324]
I'm creating a `FlexibleDecay.mk` file in `models/MODELNAME/decays` if model was created with decays. This file is included in the makefile using the syntax
```
 -include $(@CLASSNAME@_FlexibleDecay_MK)
```
This means that there's no problem if the model was created without decays and the file doesn't exist. But there is a problem a problem with `pack-$(MODNAME)-src` rule. Because a single rule cannot work in both cases. If I add `$(@CLASSNAME@_FlexibleDecay_MK)` to it, then it fails for models without decays.

**Comment by Expander** [comment]
Sorry, I don't understand why this problem exists, because we have also other `.mk` files that we generate (`betas.mk.in`) that seem to work file. Do you know where the difference is?

**Comment by wkotlarski** [comment]
It's because `@CLASSNAME@_FlexibleDecay_MK` might not exist. It's only created if we compute decays.

**Comment by Expander** [comment]
I see. What about the following solution: We always generate the file, similarly to `susy_betas.mk` and `soft_betas.mk`. However, the content of the file may be empty. Alternatively the content of the file may look similar to `templates/betas.mk.in`:
~~~.mk
LIB@ModelName@_SRC += \
@generatedBetaFunctionModules@
~~~
where `@generatedBetaFunctionModules@` may be empty.

**Comment by wkotlarski** [comment]
Apart from this decay thing everything works. I've also parallelized generation of models. This is done by taking the list of models
```
MODELS: 'CMSSM CMSSMSemiAnalytic MSSM MSSMatMGUT MSSMNoFV MSSMNoFVatMGUT CMSSMNoFV NUHMSSM lowMSSM MSSMRHN NMSSM NUTNMSSM NUTSMSSM lowNMSSMTanBetaAtMZ SMSSM UMSSM E6SSM MRSSM2 TMSSM SM HSSUSY SplitMSSM THDMII THDMIIMSSMBC HTHDMIIMSSMBC HGTHDM    IIMSSMBC MSSMEFTHiggs NMSSMEFTHiggs E6SSMEFTHiggs MRSSMEFTHiggs CNMSSM CE6SSM CE6SSM MSSMNoFVHimalaya NUHMSSMNoFVHimalaya'
```
and splitting it in half. I also sort them. This is not necessarily a good idea. The reason why one might sort models is to get same models (like all MSSMs) on the same job so that the content of the `Output` directory is created only once. But because the naming is not always consistent (like `MSSSM` and `lowMSSM` etc) this doesn't always work. Another solution would be to sort it by hand.

**Comment by wkotlarski** [comment]
Should we also delete the content of `FlexibleSUSY-generated` before the commit?

**Comment by Expander** [comment]
Yes, please!

**Comment by Expander** [comment]
I see your problem with the parallel build. In fact the same issue arises in the nightly build.  :/
My solution was to order the models by hand (although this is not optimal).

**Comment by wkotlarski** [comment]
In 9a65cfe4a6b2b93305dc7d63feed0984cd6933b1 I've implemented the simplest solution. If you're with it, please close the issue.

**Comment by Expander** [comment]
Perfect, many thanks!
