### ISSUE TITLE
generate-slha-output.sh error with NUTNMSSM

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#325]
The following command seems to execute fine
```
models/NUTNMSSM/run_NUTNMSSM.x --slha-input-file=./release/../model_files/NUTNMSSM/LesHouches.in.NUTNMSSM_1308.1333_BP1 --slha-output-file=release/2.6.0/LesHouches.out.NUTNMSSM_1308.1333_BP1
```
but `echo $? = 1`. This leads to
```
> running NUTNMSSM
> input file: LesHouches.in.NUTNMSSM_1308.1333_BP1
> output file: LesHouches.out.NUTNMSSM_1308.1333_BP1
> command: /tmp/FlexibleUpstream/models/NUTNMSSM/run_NUTNMSSM.x --slha-input-file=./release/../model_files/NUTNMSSM/LesHouches.in.NUTNMSSM_1308.1333_BP1 --slha-output-file=release/2.6.0/LesHouches.out.NUTNMSSM_1308.1333_BP1 > /dev/null 2>&1
> FAIL
```

**Comment by Expander** [comment]
I can reproduce this problem. The issue is, that the value of kappa at the GUT scale is larger than the allowed value:
~~~
Block SPINFO
     1   FlexibleSUSY
     2   2.5.0
     4   non-perturbative Kappa [|Kappa|(20650213851236984) = 4.8547678796535934 > 3.5449077018110318]
~~~

**Comment by Expander** [comment]
In `models/NUTNMSSM/NUTNMSSM_two_scale_high_scale_constraint.cpp` there is the following check:
~~~.cpp
   if (MaxAbsValue(Kappa) > 3.5449077018110318) {
      problem = true;
      model->get_problems().flag_non_perturbative_parameter(NUTNMSSM_info::Kappa, MaxAbsValue(Kappa), model->get_scale(), 3.5449077018110318);
   } else {
      model->get_problems().unflag_non_perturbative_parameter(NUTNMSSM_info::Kappa);
   }
~~~

**Comment by Expander** [comment]
One option would be to increase the value of `FSPerturbativityThreshold` in the model file.
Currently it is set to `N[Sqrt[4 Pi]]`, which may be too small for this point. What do you think?

**Comment by Expander** [comment]
I'd propose to apply the following patch:
~~~.patch
diff --git a/model_files/NUTNMSSM/FlexibleSUSY.m.in b/model_files/NUTNMSSM/FlexibleSUSY.m.in
index c5d2dad08..20a1314a5 100644
--- a/model_files/NUTNMSSM/FlexibleSUSY.m.in
+++ b/model_files/NUTNMSSM/FlexibleSUSY.m.in
@@ -79,6 +79,7 @@ InitialGuessAtLowScale = {
 };
 
 InitialGuessAtHighScale = {};
+FSPerturbativityThreshold = N[4 Pi];
 
 UseHiggs2LoopNMSSM = True;
 EffectiveMu = \[Lambda] vS / Sqrt[2];
~~~
I've just checked that it fixes the issue by relaxing the perturbativity threshold.

**Comment by wkotlarski** [comment]
I don't mind your solution but wasn't this a problem before? Or did you not care about this fail while making 2.5.0 release?

**Comment by Expander** [comment]
It failed before: https://github.com/FlexibleSUSY/FlexibleSUSY-slha/blob/master/LesHouches.out.NUTNMSSM_1308.1333_BP1
but I did not care much about it, because I think this benchmark point is screwed if kappa is so large. :)

**Comment by wkotlarski** [comment]
Cool. Thanks!

**Comment by wkotlarski** [comment]
I think `LesHouches.out.NUTNMSSM_1308.1333_BP2` suffers from the same problem, and this is not solved by your fix.

**Comment by Expander** [comment]
Yes, it also breaks on my installation. But the reason sees to be different:
~~~
Block SPINFO
     1   FlexibleSUSY
     2   2.5.0
     4   running tachyon hh
~~~
I don't think we can really fix this issue, as it seems to be a deeper physics/setup reason.
(The issue was also present in 2.5.0.)

**Comment by wkotlarski** [comment]
This is a then a problem, because the error code is returned to the shell. And the CI stops.

**Comment by Expander** [comment]
We have then the following options:
* Either we run the shell script as:
~~~
release/generate-slha-output.sh || true
~~~
* Or we don't return the error code from the script.

What do you think?

**Comment by wkotlarski** [comment]
I'd vote for the first option. But the reason why I don't like all of this is that I'm worried about the instance when the `generate-slha-output.sh` actually fails. We'll also not see it and upload garbage.

**Comment by Expander** [comment]
You are right, uploading garbage is not an option, of course.

What about the following proposals:
* If a benchmark point fails, we remove the garbage output file.
* We explicitly list the SLHA input files, which are only ones that work.

In all these cases we can properly check the exit code.

**Comment by wkotlarski** [comment]
I like the second option. It doesn't live place for surprises.

**Comment by Expander** [comment]
OK, just to recap, it would work like this:
* The script finds all configured spectrum generators (models).
* Within the script we have a hard-coded list of SLHA input files that work.

If a spectrum generator is configured and we have a corresponding model file, then we run it.

**Comment by Expander** [comment]
OK, I'll implement this.  :)

**Comment by Expander** [comment]
I've updated the script. Would you mind checking it?

One question, though: What happens about the "old" SLHA output files that are still in the repository? Should they be deleted before the new ones get added?

**Comment by wkotlarski** [comment]
Everything works. I don't know which option is better. I could remove all cards before I create new ones.

**Comment by Expander** [comment]
Personally I'd also like to remove all SLHA files and add new ones and then commit.

**Comment by wkotlarski** [comment]
Done in ad60030a7552455cc060c14377cd998eb413a7b9.

**Comment by Expander** [comment]
Thanks a lot!

**Comment by Expander** [comment]
Is this actually tested yet? I.e. do we know that it works?

**Comment by wkotlarski** [comment]
You can check branch `test` of `FlexibleSUSY-slha` and `FlexibleSUSY-generated` to see uploaded files.

**Comment by Expander** [comment]
Yes, I can see the files. But strangely, some old SLHA files are still there. Is this correct?

**Comment by wkotlarski** [comment]
I also noticed it. I've missed two models, this I've fixed.I would also like to replace `MRSSM` with `MRSSM2`. We use exclusively `MRSSM2` in all of our studies.

**Comment by Expander** [comment]
Ok, i've changed it to the `MRSSM2` model.

**Comment by wkotlarski** [comment]
This set of issues should be now solve, so I'm closing it.
