### ISSUE TITLE
exclude MSSMRHN from generate-slha-output.sh

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#327]
@Expander, seems like the MSSMRHN suffers from the same problem
```
Block SPINFO
     1   FlexibleSUSY
     2   2.5.0
     4   non-perturbative
     4   non-perturbative Yd(0,0) [Yd(0,0)(173.33999999999995) = 1.575303734501238e-05]
     5   MSSMRHN
     9   4.14.3
```

**Comment by Expander** [comment]
I see the same issue. Strangely, `Yd(0,0)` is very small.

**Comment by wkotlarski** [comment]
Yes, I also noticed it. Is there a logic error in the check?

**Comment by Expander** [comment]
Maybe, I'll have to check.

**Comment by Expander** [comment]
I've fixed the issue. It was a stupid mistake: The script used an input file with all BSM parameters set to zero, including tan(beta).

**Comment by wkotlarski** [comment]
Thanks!
