### ISSUE TITLE
preparing the 2.6.0 release

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#330]
@Expander, should we start preparing the release? Should we do it on a separate branch or directly on development?

**Comment by wkotlarski** [comment]
I'm preparing the changes on `release-2.6.0` branch. This are the changes that come to my mind:

- once we have arXiv number fill it in `README.rst`
- I've added an entry to `CHANGES.rst`
- fill `doc/observables/FlexibleDecay.rst`

Anything else comes to your mind?

**Comment by Expander** [comment]
That's all I can think of now. Well, all the tests should pass, of course (except the ones that fail from conan). :)

**Comment by wkotlarski** [comment]
I don't know how to 'do' rst. Do you understand why this
```
.. code-block::

Block DCINFO
     1   FlexibleSUSY
     2   2.6.0
     5   SM
     9   4.14.3
DECAY        25     4.01909364E-03   # hh decays
     5.88154048E-01   2          -5         5  # BR(hh -> barFd(3) Fd(3))
     2.04644925E-01   2         -24        24  # BR(hh -> conjVWp VWp)
     8.64458085E-02   2          21        21  # BR(hh -> VG VG)
     6.21678883E-02   2         -15        15  # BR(hh -> barFe(3) Fe(3))
     2.84471939E-02   2          -4         4  # BR(hh -> barFu(2) Fu(2))
     2.59621707E-02   2          23        23  # BR(hh -> VZ VZ)
     2.25173904E-03   2          22        22  # BR(hh -> VP VP)
     1.44211112E-03   2          22        23  # BR(hh -> VP VZ)
     2.63348187E-04   2          -3         3  # BR(hh -> barFd(2) Fd(2))
     2.20054695E-04   2         -13        13  # BR(hh -> barFe(2) Fe(2))
```

is not displayed correctly. [Here](https://github.com/FlexibleSUSY/FlexibleSUSY/edit/release-2.6.0/doc/observables/FlexibleDecay.rst)'s the output .

**Comment by wkotlarski** [comment]
I will still make some small editorial changes but could you please see if [this](https://github.com/FlexibleSUSY/FlexibleSUSY/blob/release-2.6.0/doc/observables/FlexibleDecay.rst) is broadly what you wanted?

**Comment by Expander** [comment]
Yes, just like that! :)

Here is my little wish list:
* Mathlink -> LibraryLink
* indentation of LibraryLink commands
* two small indentation bugs in the SLHA output file ;)
* Maybe you could also very briefly mention which symbols may be put into the `FSDecayParticles` variable.
