### ISSUE TITLE
what to do with effective couplings

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#333]
For now, I've merely disabled calculation of effective couplings. What should we do with them? Should they be removed completely or moved somewhere?

**Comment by Expander** [comment]
Good question.

Do we have tests against them of some form? If so, we could move them to the `test/` directory and kept tested against.

**Comment by wkotlarski** [comment]
We don't test against them. The set of included corrections is different, and we've uncovered some typos so I don't think that testing against them makes sense. I don't feel so bad about removing them completely because FlexibleDecay was also created by @azedarach so his spirit will still live on in FlexibleSUSY.

**Comment by Expander** [comment]
OK, if we don't test them, then they would be dead code, which is bad. Then I'd also vote for removing them.

**Comment by azedarach** [comment]
I would have absolutely no regrets about removing them. They are now superseded by the more reliable decay routines, rather than the quick implementation that came out of the diphoton project. The only thing that comes to mind would be the approach for deprecating them (following semver and keeping them in for one minor release with warnings, or just remove immediately if they are not heavily relied on?).

**Comment by pathron** [comment]
I agree, we decided they were to be deprecated so I don’t see why they should not then removed.

Generally it might be better practise to issue warnings first time, but I think we really would strongly prefer people use FlexibleDecay from its first release.  So I think  just deleting.them this time is OK.

**Comment by wkotlarski** [comment]
Ok. I'll do it after we release 2.6.0. I'll also add a warning if there's an `EFFHIGGSCOUPLINGS` block in `FlexibleSUSY.m.in`.

**Comment by wkotlarski** [comment]
@azedarach, I do have a question about `get_scalar_fermion_loop_data` function and it's sibling `get_pseudoscalar_fermion_loop_data` in the `src/effective_couplings.cpp`. These are tabulated data for the correction to fermion loop, right? We don't need it anymore but I love the implementation, so I'd use this concept for future corrections which are no avaliable analytically.

**Comment by azedarach** [comment]
Yes, that's right, they are just look-up tables used in the interpolation when there aren't analytic expressions.
