### ISSUE TITLE
getting decays over LibraryLink

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#336]
There's some odd behaviour of LibraryLink regarding `FS<model>CalculateDecays`. In the SM, the decay table is printed.
In the CMSSM the decay table is not printed to the notebook at all. The output is
```mathematica
LibraryFunction[...][0]
```
Oddly enough, the test works even though
```mathematica
FSCMSSMCalculateDecays[handle]
```
doesn't print to notebeook, the
```mathematica
Export["some_file", FSCMSSMToSLHA[handle], "String"];
```
works without any problem.
If someone with much more experience with LibraryLink would be willing to take a look at that I'd be happy to send my notebook that reproduces all of it.

**Comment by Expander** [comment]
Does this only happen in a proper Mathematica notebook, i.e. not in the Mathematica kernel?
Unfortunately I cannot run notebooks, because I just have the Wolfram Engine installed. :/
