### ISSUE TITLE
Spira's remarks

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#348]
Should we make a 2.6.1 release that would include, among others, those changes requested by Spira or should we only backport commit c00c3d9 into the main?

**Comment by Expander** [comment]
I would prefer to make a new release 2.6.1.

**Comment by wkotlarski** [comment]
Me to.

**Comment by pathron** [comment]
Hi Wojtek, I think you forgot to tell me what the outcome was from the discussion on how to handle spira's remarks?

I also think we should make a new 2.6.1 release, though I don't  think I really understand what the alternative was :).

**Comment by wkotlarski** [comment]
We've added a switch such that the 2-loop QCQ correction to `\Phi \to Z \gamma` is only aplied if `m_Z/m_\Phi < 0.75`.

**Comment by pathron** [comment]
is that to address his point 2? Do we do anything for his point 1?  Maybe we should discuss this by email though as it can be a paper issue rather than a code one?

**Comment by wkotlarski** [comment]
Point 1 has been also addressed. I've made changes to section with SM comparison.

**Comment by wkotlarski** [comment]
@Expander, will you prepare a release?

**Comment by Expander** [comment]
Yes, I'll prepare it tomorrow, if that is okay.

Wojciech Kotlarski ***@***.***> schrieb am Mi., 7. Juli 2021,
21:34:

**Comment by Expander** [comment]
Can I directly use the `development` branch, or should other PRs be merged before?

**Comment by pathron** [comment]
OK thanks, the changes look good!

**Comment by wkotlarski** [comment]
Thanks everybody!
