### ISSUE TITLE
Checks for shell scripts

### ISSUE THREAD

**Issue by uukhas** [FlexibleSUSY/FlexibleSUSY#381]
Recently I have found a tool, which might help to prevent some obvious/non-obvious errors for shell scripts.
It can be found [here](https://github.com/koalaman/shellcheck#how-to-use).
It is also suggested by google shell code style, so it might be useful for us as well.

**Comment by Expander** [comment]
Very nice, thanks for the hint!
In which way should we use the tool? Do you have a proposal?

**Comment by uukhas** [comment]
* One can include the separate tests for script files during our github-tests and use the part "In your build or test suites" from https://github.com/koalaman/shellcheck#how-to-use.
* As another one we can consider some git hookups on local machines
* We can also just use some Wiki suggestion link with some brief example of how to use it.

**Comment by Expander** [comment]
As criteria I'd suggest to chose an option that requires minimal maintenance, is as automatic as possible and does not require additional tasks to be done by a user/developer. I'd say your options 1 and 3 meet these criteria. Option 1 may be the best, but only if it is very simple to do and also very easy to maintain. What do you think?

**Comment by wkotlarski** [comment]
If you want I can easily add a `shellscript` test. Imidiatelly I see that it complains about the `configure` script
```
In configure line 1795:
    [ -n ${eigen_name} ] && \
         ^-----------^ SC2070: -n doesn't work with unquoted arguments. Quote or use [[ ]].


In configure line 2086:
        [ -n ${gm2calc_name} ] && \
             ^-------------^ SC2070: -n doesn't work with unquoted arguments. Quote or use [[ ]].


In configure line 2198:
        [ -n ${himalaya_name} ] && \
             ^--------------^ SC2070: -n doesn't work with unquoted arguments. Quote or use [[ ]].


In configure line 2350:
   [ -n ${looptools_name} ] && \
        ^---------------^ SC2070: -n doesn't work with unquoted arguments. Quote or use [[ ]].


In configure line 2423:
   [ -n ${collier_name} ] && \
        ^-------------^ SC2070: -n doesn't work with unquoted arguments. Quote or use [[ ]].


In configure line 2645:
    [ -n ${tsil_name} ] && \
         ^----------^ SC2070: -n doesn't work with unquoted arguments. Quote or use [[ ]].
```

**Comment by uukhas** [comment]
@wkotlarski, I would love it. 
`sh` and `bash` are very counterintuitive things, so that most people (me, in particular) would like to have some help with it.

And, as you have mentioned above, we already get some warnings, like those unquoted arguments.

**Comment by wkotlarski** [comment]
I will set it up but I will not fix those errors. I don't know bash and it's not a skill I desire to have :p

**Comment by uukhas** [comment]
@wkotlarski, I will fix them and make a PR. I just do not have in mind, how many `.sh` files we have. Can you please share a list of files, which you will be checking?

**Comment by wkotlarski** [comment]
#385 runs 
```bash
shellcheck -S error configure
```
We can start from there (adding more files to check, also dealing with warnings etc.).

**Comment by Expander** [comment]
> @wkotlarski, I will fix them and make a PR.

Yes, let's fix them! :)

**Comment by wkotlarski** [comment]
@uukhas, you can get the list of files we test for with
```bash
ls configure createmodel install-sarah createaddon config/*.sh utils/*.sh test/test_*.sh
```

**Comment by wkotlarski** [comment]
@uukhas, can we close this?

**Comment by uukhas** [comment]
@wkotlarski, I have fixed errors and warnings. Do we want to fix style-warnings as well?  Like 
Instead of ``$A`` use ``"$A"``?

**Comment by wkotlarski** [comment]
@Expander should decide. I still don't care :smile:

**Comment by Expander** [comment]
Writing `"$A"` instead of `$A` is generally better.
(But be careful, depending on the context the two may not be exchangeable.)

**Comment by uukhas** [comment]
I agree with that. The point is that we have a lot of similar suggestions. By a lot I would estimate several hundreds. And we can, of course, forget about them, because everything works just fine.

**Comment by Expander** [comment]
Let's go with this pragmatic approach. :)
I'd suggest to do such refactorings as we change the code.

**Comment by uukhas** [comment]
Then I close this issue.
