### ISSUE TITLE
Link for tutorials.

### ISSUE THREAD

**Issue by uukhas** [FlexibleSUSY/FlexibleSUSY#397]
We can mention some links for tutorials from the Computational Tools of previous years (and some other ones, probably):

* From [Thu 05/11 2020](https://indico.cern.ch/event/955391/timetable/#20201105.detailed)
* From [Fri 26/11 2021](https://indico.cern.ch/event/1076291/timetable/#20211126.detailed)

This might be related to #221.

**Comment by Expander** [comment]
I have added the links to the `Tutorials` section in our Wiki:
https://github.com/FlexibleSUSY/FlexibleSUSY/wiki/Documentation#tutorials
