### ISSUE TITLE
No documentation for `tadpole`

### ISSUE THREAD

**Issue by uukhas** [FlexibleSUSY/FlexibleSUSY#401]
It seems that one can use something like ``FlexibleSUSY`tadpole[1]`` in `FlexibleSUSY.m`, but I have found no documentation about this possibility.

Should it be mentioned somewhere?

**Comment by Expander** [comment]
Good idea! I think it would fit somewhere here:
https://github.com/FlexibleSUSY/FlexibleSUSY/blob/master/doc/model_file.rst#boundary-conditions

**Comment by Expander** [comment]
I've added the documentation of the `tadpole` symbol as described.
