### ISSUE TITLE
`conj` is not applied appropriately

### ISSUE THREAD

**Issue by uukhas** [FlexibleSUSY/FlexibleSUSY#403]
Expressions
```mathematica
In[1]:=      sum[i, 1, 2, a[i]]
        conj[sum[i, 1, 2, a[i]]]
```
produce the same result
```mathematica
Out[1]= sum[i, 1, 2, a[i]]
        sum[i, 1, 2, a[i]]
```
however, I would personally expect to get `sum[i, 1, 2, conj@a[i]]` in the second scenario.

I have no idea, whether this assumption was made by anyone else in the code, but I think that it should be written explicitly somewhere.

**Comment by Expander** [comment]
I agree, this looks incorrect if the expression summed over contains complex numbers. By grepping through `meta/*.m`
~~~.sh
rg -w 'conj' meta | rg sum
~~~
I could only find a replacement rule in `meta/TreeMasses.m` in `IsHermitian`. This, however, is just a local rule and should not affect the global behaviour. So, I suspect this behaviour comes from within SARAH.

**Comment by Expander** [comment]
I've added a warning entry for us in our wiki:
https://github.com/FlexibleSUSY/FlexibleSUSY/wiki/SARAH
