### ISSUE TITLE
are we allowed to use all unicode characters in printouts from FS

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#414]
i.e. can I write
```mathematica
Print["Calculating l→lγ"];
```

**Comment by Expander** [comment]
Yes, that usually works fine on modern terminals.
You may check how it looks when you pipe the output to a file, though.

**Comment by wkotlarski** [comment]
Thanks! We are finally allowed to have nice things! I'll make some changes in spare time.
