### ISSUE TITLE
warning: advanced initialization in Eigen might confuse

### ISSUE THREAD

**Issue by uukhas** [FlexibleSUSY/FlexibleSUSY#429]
There is the following way to initialize an array:
```C++
Eigen::Array<double,2,1> a;
a << 1, 2;
std::cout << a << "\n";
```
And the output is as one would assume:
```C++
1
2
```
So, I have immediately concluded that ``<<`` acts as ``=``, i.e. the right side is calculated at the same time and only then the substitution is done. This is **WRONG**:
```C++
Eigen::Array<double,2,1> a;
a << 1, 2;
a << a[0] + a[1], a[0];
std::cout << a << "\n";
```
returns
```C++
3
3
```
and not ``3 1``. So that every comma-separated element is calculated right after the update in corresponding ``a`` element.

**Comment by Expander** [comment]
You are right, this is a potential pitfall. Did this cause problems in some parts of the code?

**Comment by uukhas** [comment]
@Expander, this caused a problem for `l_i->3l_j` decays in the code which is **not** fully merged in FlexibleSUSY. 
About other places I do not know yet.

**Comment by pathron** [comment]
This is just eigen though, not sure what we can do other than not use the << incorrectly .  Is it documented somewhere in eigen that it works this way?

**Comment by uukhas** [comment]
Dear @pathron, [here](https://eigen.tuxfamily.org/dox/group__TutorialAdvancedInitialization.html) they do not use things similar to ``a << a[0] + a[1], a[0];``.

What we can do is to make sure that we know about this "tricky"  behavior (maybe contact eigen developers as well and ask them to add this case in the linked page). 

We can add this warning to our developer wiki.

**Comment by pathron** [comment]
Yes I also agree with that.  I also agree with @uukhas  that putting a note in our wiki here to warn other FS people about it is also helpful.

**Comment by Expander** [comment]
I have created the wiki page https://github.com/FlexibleSUSY/FlexibleSUSY/wiki/Eigen-library to warn us about this issue.
