### ISSUE TITLE
FlexibleDecay broke CMSSMSemiAnalytic_consistent_solutions test

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#442]
I believe the problem comes from `MODELNAME_decay_amplitudes.hpp`. Some things with the same name are included in `CMSSMSemiAnalytic_consistent_solutions.cpp` twice.

**Comment by wkotlarski** [comment]
@Expander, this is the same problem I've stumbled upon when trying to implement interface to `HiggsTools`. In `MODELNAME_decay_amplitudes` we have functions like this
```cpp
template <class Field_in, class Field_out_1, class Field_out_2>    
struct Two_body_decay_amplitude_type<    
   Field_in, Field_out_1, Field_out_2,    
   std::enable_if_t<CMSSM_cxx_diagrams::fields::is_scalar<Field_in>::value &&    
                           CMSSM_cxx_diagrams::fields::is_scalar<Field_out_1>::value &&    
                           CMSSM_cxx_diagrams::fields::is_scalar<Field_out_2>::value>> {    
   using type = Decay_amplitude_SSS;    
};
```
They know about the model only via the `enable_if`. This means that if you load somewhere two models at the same time you get duplicate definitions. There are 2 solutions to this

1. dumb: add model name to function name, e.g. `MODELNAME_Two_body_decay_amplitude_type`
2. elegant: abstract away `is_scalar`. If `is_scalar` was not a member of `MODELNAME_cxx_diagrams::fields` but took every field and internally called specific `MODELNAME_cxx_diagrams::fields::is_scalar` this would work. 

I like idea 2 (it seems elegant) but I don't know if it's possible. Thoughts?

**Comment by wkotlarski** [comment]
The idea of point 2 is that

1. `Two_body_decay_amplitude_type` would go to src because it would become model independent
2. We would had trait `is_scalar` that somehow would inherit from all different `_cxx_diagrams::fields::is_scalar` (don't know yet if that's possible)

**Comment by wkotlarski** [comment]
Jobst put things like `bar`, `conj`, `is_scalar` etc. in `fields.hpp.in` but couldn't they be moved outside, lets say to `src`? They are model independent. What is model specific, and what has to go to `fields.hpp.in` are specializations, like
```cpp
template<>    
struct is_vector<SM_cxx_diagrams::fields::VG > : public std::true_type {};
```
Sorry for all the questions but before I spend 10h trying to implement something I'd like to at least ask if makes any sense. Would it be possible to move all generic stuff (`is_scalar`, `bar`, `conj` etc) to `src/cxx_qft/fields.hpp` and keep in `models/MODELNAME/cxx_qft/MODELNAME_fields.hpp` only specializations?

**Comment by Expander** [comment]
I also like your proposal 2. Since we're talking about structs (not functions), template specializations should be possible. I.e. having generic `is_scalar` and several model-specific template specializations should be possible. I also have the feeling this would be best and also very clean.

Also, having more of this stuff in `src/` would be better in my opinion, because it can be changed w/o re-building the models.
