### ISSUE TITLE
There are duplicate symbol error messages

### ISSUE THREAD

**Issue by iolojz** [FlexibleSUSY/FlexibleSUSY#45]
When running `make` (internally ```Needs["FlexibleSUSY`]``` in `models/XXX/start.m` there are two error messages:
- ```Susyno`LieGroups`m2::shdw```: Symbol `m2` appears in multiple contexts ```{Susyno`LieGroups`,SARAH`};``` definitions in context ```Susyno`LieGroups` ``` may shadow or be shadowed by other definitions.
- ```Susyno`LieGroups`M::shdw```: Symbol `M` appears in multiple contexts ```{Susyno`LieGroups`,FlexibleSUSY`,SARAH`};``` definitions in context ```Susyno`LieGroups` ``` may shadow or be shadowed by other definitions.

**Comment by iolojz** [comment]
Yes, but my SARAH version might be too old. I will try again with a recent version.

**Comment by Expander** [comment]
Is this issue still there with the recent SARAH version on your machine?

**Comment by iolojz** [comment]
I just checked again. No, I cannot reproduce the issue with SARAH 4.14.1.
