### ISSUE TITLE
There is a file not found error message

### ISSUE THREAD

**Issue by iolojz** [FlexibleSUSY/FlexibleSUSY#46]
When running `make` (internally `Start["XXX"]` in `models/XXX/start.m`) with a `SARAH` default model that does not lie in the `sarah` directory (e.g `SM`), there is the error message:

```FileByteCount::fdnfnd```: Directory or file ```/home/h7/s3377910/FSUpstream/sarah/XXX/XXX.m``` not found.

**Comment by Expander** [comment]
Sorry, I cannot reproduce this issue on the current development branch with Mathematica 9 and SARAH 4.14.0, using SARAH's `SM` model. Which configuration do you use?

**Comment by iolojz** [comment]
Hm, maybe my SARAH version is too old then... I will try again with a recent version.

**Comment by Expander** [comment]
Is this issue still there with the recent SARAH version on your machine?

**Comment by iolojz** [comment]
Yes, with SARAH version 4.14.4, I get the following output:

Preparing arrays
 ... checking Directory: /home/h7/s3377910/FSUpstream/sarah

FileByteCount::fdnfnd: 
   Directory or file /home/h7/s3377910/FSUpstream/sarah/SM/SM.m not found.
 ... checking Directory: /home/h7/s3377910/.Mathematica/Applications/SARAH/Models/
Model files loaded   
  Model    : SM
  Author(s): F.Staub
  Date     : 2014-11-06

**Comment by Expander** [comment]
I think what you see may not a bug, but just an internal message from SARAH (although I'm wondering why I don't see it):  In `models/SM/start.m` we have
~~~
workingDirectory = Directory[];

SARAH`SARAH[InputDirectories] = {
    FileNameJoin[{workingDirectory, "sarah"}],
    ToFileName[{$sarahDir, "Models"}]
};
~~~

So, first SARAH should search for the SM model inside the directory `./sarah/`. If it cannot be found there, it shall look in the `$sarahDir/Models` directory. It seems that in your case SARAH prints an error message if it cannot find the model in `./sarah/`. On my machine it prints:

~~~
Preparing arrays
 ... checking Directory: /home/avoigt/research/FlexibleSUSY/sarah
 ... checking Directory: /home/avoigt/mathematica/SARAH-4.14.1/Models/
Model files loaded   
  Model    : SM
  Author(s): F.Staub
  Date     : 2014-11-06
~~~

One question: The error message seems to come from `FileByteCount::fdnfnd`. Could it be that this is a message that is only available in Mathematica > 9?

**Comment by iolojz** [comment]
That sounds possible! If I run e.g `FileByteCount["lajsbdasjhd"]` I get 

FileByteCount::fdnfnd: Directory or file lajsbdasjhd not found.

an the return value `$Failed`. What do you get?

**Comment by Expander** [comment]
If I understand correctly, SARAH executes (in `SARAH.m`):
~~~
Off[FileByteCount::nffil];
FileByteCount["lajsbdasjhd"];
~~~
When I execute this, I get no error message, but (as in your case) `FileByteCount["lajsbdasjhd"]` returns `$Failed`. What do you get?

**Comment by iolojz** [comment]
I still get the error message. So you are right, it is a feature of my Mathematica version.
