### ISSUE TITLE
Check and enable Bar-Zee 2-loop diagrams

### ISSUE THREAD

**Issue by Expander** [FlexibleSUSY/FlexibleSUSY#473]
FS generates 2-loop Bar-Zee diagrams to calculate $a_\mu$.
However, these diagrams are not validated yet and are thus not enabled (commented out).

Proposal: Check the diagrams (for example against the known MSSM and/or THDM contribution) and enable them.

**Comment by wkotlarski** [comment]
Thanks for thinking about this. I think it would be good to do it after the #427 goes in. This PR restructures some parts of the Bar-Zee calculation.

**Comment by Expander** [comment]
Ok, I'll look at #427 first then.

**Comment by wkotlarski** [comment]
No.

**Comment by wkotlarski** [comment]
Something to think about:
- should we let users turn those contributions on and off
- should we add them to result or print them separately

**Comment by pathron** [comment]
This sounds like a very nice idea!  Maybe checking them against MSSM and THDM can be a small project for a student?  Regarding Wojtek's questions, I would suggest using a loop level flag for amu e.g, "amu_loop_level" and including them in the results if its set to 2 or higher.  The user can switch the flag between 1 and 2 if they want to know how big they are.    If there are no concerns from validation and discussions about these in other models, the default value for the flag can be 2.

**Comment by wkotlarski** [comment]
Should we add it as flag 32? Or maybe we should use FS 3.0 as an opportunity to restructure flags controling observables. We discussed once about a separate block with flags controling observables.

**Comment by Expander** [comment]
I like the idea of having a loop order flag to control the loop corrections to $a_\mu$.

**Comment by Expander** [comment]
I'm not against adding new flags for observables to a separate block, but I'd recommend to keep backwards compatibility if possible or at least warn the user if he/she set flags that we have moved.
