### ISSUE TITLE
create global aliases for particles

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#477]
The are parts of the code where we specialize templates on SM fields. Examples are:
- the g-2 Barr-Zee calculation where we need to identify the Z boson
  `using VZ = fields::VZ;`
- `FlexibleDecay` where we specialize on all SM fields
   `using H = fields::hh;`
    `using AH = fields::Ah;`
    `using W = fields::VWm;`
    `using Z = fields::VZ;`
    `using G = fields::VG;`
    `using A = fields::VP;`
    `using lep = fields::Fe;`
    `using uq = fields::Fu;`
    `using dq = fields::Fd;`

Maybe it would be useful to create one include file with all those aliases, e.g. for every model create a `models/MODEL/particle_aliases.inc`. If you're ok with this, we also need to decide on field names we'd like to use.

**Comment by Expander** [comment]
Excellent idea! I'd propose to call the file `models/<model>/particle_aliases.hpp`.

**Comment by wkotlarski** [comment]
Closed with #505.
