### ISSUE TITLE
configure script fails to track correct FeynArts version

### ISSUE THREAD

**Issue by SoundSonic1** [FlexibleSUSY/FlexibleSUSY#48]
If i set --enable-feynarts, the configure script reads the current FeynArts version via
$FeynArts = 3.10 = 3.1 < 3.9
and therefore the version does not pass the requirement.

**Comment by Expander** [comment]
Many thanks for reporting this issue! Do you know in which FeynArts version it will be fixed?

**Comment by SoundSonic1** [comment]
Apparently, he changed it yesterday after i told him the issue. We are going to adapt to this new format.

**Comment by Expander** [comment]
> We are going to adapt to this new format.

Are you preparing a patch?

**Comment by Expander** [comment]
Many thanks for fixing this!
