### ISSUE TITLE
backporting changes to l->l'gamma from uukhas/feature-new-observables 

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#511]
@uukhas, would it be possible to make a PR with changes you've made to the calculation of $l \to l' \gamma$?

**Comment by uukhas** [comment]
@wkotlarski, yes but in some months as now I am doing something different, would it be ok?

**Comment by wkotlarski** [comment]
No problem. We have time. This is mostly to set a plan how we proceed.

**Comment by uukhas** [comment]
Addressed in #583
