### ISSUE TITLE
extracting parameters and mixing matrices from an expression

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#520]
@Expander, SARAH produces expressions for scattering matrix eigenvalues in the form as
```mathematica
((g1^2 + g2^2)*((pmass[hh[in1]]^4 + (s - pmass[hh[in2]]^2)^2 - 2*pmass[hh[in1]]^2*(s + pmass[hh[in2]]^2))*(pmass[hh[out1]]^4 + (s - pmass[hh[out2]]^2)^2 - 2*pmass[hh[out1]]^2*(s + pmass[hh[out2]]^2)))^(1/4)*Sqrt2[in1, in2]*Sqrt2[out1, out2]*(-(((g1^2 + g2^2)*s*uChan*(Log[-((-s^2 + (pmass[hh[in1]] - pmass[hh[in2]])*(pmass[hh[in1]] + pmass[hh[in2]])*(pmass[hh[out1]] - pmass[hh[out2]])*(pmass[hh[out1]] + pmass[hh[out2]]) + s*(-2*pmass[hh[1]]^2 + pmass[hh[in1]]^2 + pmass[hh[in2]]^2 + pmass[hh[out1]]^2 + pmass[hh[out2]]^2) + Sqrt[(pmass[hh[in1]]^4 + (s - pmass[hh[in2]]^2)^2 - 2*pmass[hh[in1]]^2*...
```
I can catch masses by looking for `pmass` head. Any idea how to catch couplings and mixing matrices so that I could create C++ definitions? Maybe we already have such a helper function, that would return a list of all symbols from an expression.

**Comment by Expander** [comment]
A useful function to get all parameters (categorized w.r.t. their type is)
~~~
Parameters`FindAllParametersClassified[expr_, exceptions_:{}]
~~~
it returns a list of replacement rules with the symbols that appear in `expr`. `exceptions` is a list of symbols that should be excluded. The result has the form
~~~
          {
               FSModelParameters -> ...,
               FSInputParameters -> ...,
               FSOutputParameters -> ...,
               FSPhysicalOutputParameters -> ...,
               FSPhases -> ...,
               FSDerivedParameters -> ...,
               FSExtraParameters -> ...
           }
~~~
If you want to find all parameters, you could just use ``FindAllParameters``.

**Comment by wkotlarski** [comment]
Perfect! One question though. For the SM `FSModelParameters` contains `\[Lambda]`. But internally we map it to `Lambdax`. Where is it defined?

**Comment by wkotlarski** [comment]
Ok, I think I got everything working. Got input parameters from `FSModelParameters` and mixing matrices from `FSOutputParameters`. Hope nothing else appears in more complicated models. If so, I will reopen this issue. Thanks!
