### ISSUE TITLE
CXXDiagrams cannot handle triple gauge boson couplings

### ISSUE THREAD

**Issue by SoundSonic1** [FlexibleSUSY/FlexibleSUSY#54]
I firmly believe that CXXDiagrams cannot handle the triple gauge bosons couplings. However, they are required in a lot of processes.

**Comment by wkotlarski** [comment]
I also believe that we're also missing 4-vector and vector 2 ghosts ones.

**Comment by wkotlarski** [comment]
@iolojz, @azedarach implemented all the remaining vertices in [this](https://github.com/FlexibleDecay/FlexibleSUSY/tree/feature-decays) branch. Maybe they can be lifted?

**Comment by azedarach** [comment]
It would certainly be much cleaner if the remaining vertices were implemented consistently with the existing ones. I think the implementation in the decays branch could serve as a starting point, but it would need to be brought into line with that already present in the development branch - as I am relatively unfamiliar with the internals of CXXDiagrams, I split things up while trying to work out how to add the missing cases and may have introduced bugs.

**Comment by iolojz** [comment]
This is fixed by https://github.com/FlexibleSUSY/FlexibleSUSY/pull/62.
