### ISSUE TITLE
missing header

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#58]
The `context_base.hpp.in` internally creates an instance of class `@ModelName@_mass_eigenstates`. Shouldn't `context_base.hpp.in` then include `@ModelName@_mass_eigenstates.hpp`?

**Comment by Expander** [comment]
Yes, definitely!

**Comment by Expander** [comment]
@wkotlarski  or @iolojz, could you please provide a fix?

**Comment by wkotlarski** [comment]
Fixed in #60. @iolojz, check if you agree.

**Comment by Expander** [comment]
Perfect, many thanks!

**Comment by iolojz** [comment]
Absolutely, I actually ran into the same issue myself yesterday ^^
The fix looks fine.
