### ISSUE TITLE
Making tests faster

### ISSUE THREAD

**Issue by uukhas** [FlexibleSUSY/FlexibleSUSY#585]
We almost never change `SARAH` models that we use in CI tests while filling of the `Output/` directory takes a lot of time. 

Should we cache the content of this directory somewhere?

To be sure that the content of `Output/` is up to date, we can hash the content of `SARAH` itself to be sure that nothing is changed from its side and re-generate the content of the `Output/` directory only when `SARAH` changes.

**Comment by wkotlarski** [comment]
Hi Vova. Just to be sure. The `Output` content is independent of changes to `model_files`, right? If yes, than we could use the [restore action](https://github.com/actions/cache?tab=readme-ov-file#using-a-combination-of-restore-and-save-actions).

**Comment by uukhas** [comment]
Good question. If ``model_files`` do not alter ``SARAH`` output, then ``Output`` content should be independent from ``model_files``.
