### ISSUE TITLE
minimal FormCalc version

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#612]
@uukhas, @Expander discovered that NPointFunctions doesn't work with FeynArts 3.9 (#611) so I've raised the required version to 3.11 (71b9167). What about FormCalc. Is it true that the minimal required version is 9.5?

**Comment by uukhas** [comment]
Thank you for letting me know about `FeynArts`, I will check it.
I remember that there was a change in the `FormCalc` definitions for some vertices or momenta representation, or similar. And I definitely remember that I checked several version some years ago, so it should be as written. 

I am wondering about `FeynArts`, though, look at my comment in #611.

**Comment by wkotlarski** [comment]
Finally fixed in 70b351f4c760c3794109a432f7457a6dc82d85a2. See discussion in #611.
