### ISSUE TITLE
cant find ipython

### ISSUE THREAD

**Issue by liu20001028** [FlexibleSUSY/FlexibleSUSY#617]
/usr/bin/ld: 找不到 -lpython3.10: 没有那个文件或目录
collect2: error: ld returned 1 exit status
make: *** [models/MRSSM/module.mk:339：models/MRSSM/run_MRSSM.x] 错误 1
make: *** 正在等待未完成的任务....
/usr/bin/ld: 找不到 -lpython3.10: 没有那个文件或目录
collect2: error: ld returned 1 exit status
make: *** [models/MRSSM/module.mk:339：models/MRSSM/run_cmd_line_MRSSM.x] 错误 1
/usr/bin/ld: 找不到 -lpython3.10: 没有那个文件或目录
collect2: error: ld returned 1 exit status
make: *** [models/MRSSM/module.mk:339：models/MRSSM/scan_MRSSM.x] 错误 1
/usr/bin/ld: 找不到 -lpython3.10: 没有那个文件或目录
collect2: error: ld returned 1 exit status
make: *** [models/MRSSM/module.mk:343：models/MRSSM/MRSSM_librarylink.so] 错误 1

**Comment by liu20001028** [comment]
i dont know  why be this

**Comment by wkotlarski** [comment]
After that, could you check if the code on `fix-python3-libdir` branch also suffers from this bug?

**Comment by liu20001028** [comment]
l  found some problenms 
1. " ERROR: Version conflict: Conflict between boost/1.83.0 and boost/1.75.0 in the graph.
Conflict originates from gm2calc/2.1.0" 
And 
 "ERROR: Version conflict: Conflict between boost/1.83.0 and boost/1.75.0 in the graph.Conflict originates from gm2calc/2.2.0"
boost 1.75 seems to be conflect with gm2.1   2.2
2 .   IN   "conanfile.txt"  the code [Option]  shoud be   
  "[options]
boost/*:bzip2=False
boost/*:error_code_header_only=False
boost/*:fPIC=True
boost/*:filesystem_no_deprecated=False"   this form   
3.   Also in    "conanfile.txt"  the code   shound be     "[generators]
CMakeDeps
CMakeToolchain
MakeDeps
PkgConfigDeps"  he said  cmake  make pke  doesnt  use 
Maybe  the problem  because of my conan is version2
4.  /home/lhy/software/anaconda3/envs/FlexibleSUSY/lib/libpython3.10.so
/home/lhy/software/anaconda3/envs/FlexibleSUSY/lib/libpython3.10.so.1.0
l have it   but  it doennt  find

**Comment by liu20001028** [comment]
ok  l find my problem solution     I   take another  venv   instead of conda   Thanks
