### ISSUE TITLE
Key 1 in Block MODSEL currently not supported Unrecognized entry in block MODSEL: 2 cannot convert string to double

### ISSUE THREAD

**Issue by liu20001028** [FlexibleSUSY/FlexibleSUSY#622]
when i input  
LesHouches.in.MRSSM
then      "Key 1 in Block MODSEL currently not supported
Unrecognized entry in block MODSEL: 2
cannot convert string to double"

here is my block 
Block MODSEL         #
    1      0        #  1/0: High/low scale input
    2     1         # Boundary Condition
    6     1         # Generation Mixing
  

is a  problem with a string  which cant   identificat   “1”？

**Comment by Expander** [comment]
This is expected, i.e. `MODSEL[2]` is not supported in FlexibleSUSY. Per convention, `MODSEL[2]` allows to switch between different boundary conditions in the MSSM. In FlexibleSUSY, however, you specify the explicit form of one boundary condition in the model file `model_files/<model>/FlexibleSUSY.m.in`. So, from the FlexibleSUSY perspective it makes no sense to switch between different BCs, as there is only one defined per model. :)
