### ISSUE TITLE
[BUG DESCRIPTION]

### ISSUE THREAD

**Issue by uukhas** [FlexibleSUSY/FlexibleSUSY#625]
### Bug description
It seems that the file `sarah/THDM-I/THDM-I.m` contains wrong Yukawa couplings, as all of them are with `H2`:
```
line 78: + Yd conj[H2].d.q + Ye conj[H2].e.l + Yu H2.u.q
```

### Anything else
I did not check the whole file, only this line.

**Comment by wkotlarski** [comment]
Are you sure? I've never worked on it but according to [this Tab. 1](https://arxiv.org/pdf/1106.0034) that's how THDM type I works.

**Comment by uukhas** [comment]
Yes, I was too fast. I just have found a misprint somewhere else.
