### ISSUE TITLE
bug in self_energy_hh_1loop_deriv_p2

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#629]
Hi @Expander. I've rewritten the `self_energy_hh_1loop_deriv_p2` and I think I found some bugs in the previous implementation. I though I should let you know since you're now working on it too. For example, the Higgs self energy has the following term
```mathematica
4*(-1/2 + B0[p^2 , Mass2[VWp], Mass2[VWp]]) conj[Cp[hh, conj[VWp], VWp]])
```
which gets translated to
```cpp
result += 2*AbsSqr(CphhconjVWpVWp())*(-1 + 2*DB0(Sqr(p),Sqr(MVWp),Sqr(MVWp)));
```
This is wrong. I have a corrected routine which gives the expected result, which is
```cpp
result += 4*AbsSqr(CphhconjVWpVWp())*DB0(Sqr(p),Sqr(MVWp),Sqr(MVWp));
```
I'm in Dresden right now with a new laptop on which I don't have my private ssh key so I cannot make a PR. But I'll do it on Monday..

**Comment by Expander** [comment]
Ouch! Thanks a lot for finding this bug! Please feel free to merge this PR on Monday. It is indeed highly relevant for Dominik, Johannes and me right now!

**Comment by wkotlarski** [comment]
Here are the lines that need to change.
Old code:
```cpp
   result += 2*AbsSqr(CphhconjVWpVWp())*(-1 + 2*DB0(Sqr(p),Sqr(MVWp),Sqr(MVWp)));
   result += AbsSqr(CphhVZVZ())*(-1 + 2*DB0(Sqr(p),Sqr(MVZ),Sqr(MVZ)));
   result += AbsSqr(CpAhhhVZ())*F0(Sqr(p),Sqr(MAh),Sqr(MVZ));
   result += 2*AbsSqr(CphhHpconjVWp())*F0(Sqr(p),Sqr(MHp),Sqr(MVWp));
   result += -2*CphhhhconjVWpVWp()*Sqr(MVWp);
   result += -(CphhhhVZVZ()*Sqr(MVZ));
```
new code:
```cpp
   result += 4*AbsSqr(CphhconjVWpVWp())*DB0(Sqr(p),Sqr(MVWp),Sqr(MVWp));
   result += 2*AbsSqr(CphhVZVZ())*DB0(Sqr(p),Sqr(MVZ),Sqr(MVZ));
   result += AbsSqr(CpAhhhVZ())*DF0(Sqr(p),Sqr(MAh),Sqr(MVZ));
   result += 2*AbsSqr(CphhHpconjVWp())*DF0(Sqr(p),Sqr(MHp),Sqr(MVWp));
```

**Comment by Expander** [comment]
Thanks! I guess in your PR on Monday you will make the corresponding modification to the meta code, right?
