### ISSUE TITLE
possible problem with linking against LoopTools v2.15

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#65]
If I link against `LoopTools` v2.15 I'm getting the following error
```
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /home/wojciech/HEP-software/gcc/LoopTools-2.15/lib64/libooptools.a(solveC.o): undefined reference to symbol 'cabsq@@QUADMATH_1.0'
/usr/lib64/gcc/x86_64-suse-linux/8/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/libquadmath.so.0: error adding symbols: DSO missing from command line
```
The `LoopTools` is compiled in double precision. The solution for me is to add `quadmath` to the linker. Has anyone ever seen something like that and can confirm this error?

**Comment by Expander** [comment]
I have not seen this error before. Which compiler are you using? Could you please paste the exact linking command that is used (just copy it from the FS build output)? Did you add `libquadmath` via `./configure --with-shared-ldlibs=lquadmath`?

**Comment by Expander** [comment]
This problem is now fixed when installing LoopTools via `conan`.
