### ISSUE TITLE
potential error in loop function interface

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#66]
@Expander, are those spaces before `include` in `pv.cpp` in 
```c++
#ifdef ENABLE_LOOPTOOLS
#  include <clooptools.h>
#elif defined(ENABLE_FFLITE)
#  include "fflite.hpp"
#else
#  include "numerics.h"
#endif
```
intentional?

**Comment by Expander** [comment]
Yes, they are intentional because they improve readability. All tested C preprocessors accept spaces between `#` and `include`.

**Comment by wkotlarski** [comment]
Oh, thanks! Didn't know it works like this.
