### ISSUE TITLE
meta phase for CSE6SSM might fail

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#76]
Is it possible to bullet proof the makefile for his? Maybe check that no code was emitted? Same way how we check that non zero error code means failure?

**Comment by Expander** [comment]
I think there is no sane way to check that no code was omitted, because Mma may crash at any step, even after some files have been written.

But I can check what make does when a process segfaults etc. Maybe one can catch this?

**Comment by pathron** [comment]
You mean that it could crash half way through the generation of last file so you get incomplete C++ files?  I feel like it would still be useful to have a check that all files that were supposed to be generated were actually created though.  Simply catching when mathematica crashes would of course be better for a full proof solution to this issue though.

**Comment by wkotlarski** [comment]
@Expander, we check if the mathematica part doesn't emit a code 1 back to a shell. I assume, that a successful run emits code 0. But what happens when the meta phase crashes?

**Comment by Expander** [comment]
You are right, if the exit code is non-zero, `make` stops. Apparently this does not happen when Mma crashes, which seems strange.  According to
https://stackoverflow.com/questions/14599670/what-error-code-does-a-process-that-segfaults-return
the exit code should be non-zero when a segfault appears. But I'm not sure what happens in practice when Mma crashes.

Anyway, I've checked with the simple program
~~~
#include <iostream>

int main() {
   int* p = 0;
   std::cout << *p;
}
~~~
and the makefile:
~~~
run:
	@echo "starting"
	./a.out
	@echo "done"
~~~
that `make` indeed stops:
~~~
$ make
starting
./a.out
makefile:2: recipe for target 'run' failed
make: *** [run] Segmentation fault
~~~

**Comment by uukhas** [comment]
I tried to build CSE6SSM model with FlexibleSUSY installed (today) directly from GitHub and I also got an error. The same happened with FlexibleSUSY-2.3.0 installed from hepforge.

**Comment by wkotlarski** [comment]
This works now for me with mathematica 12. @uukhas is trying to confirm it. If yes, we could close it and accept that one has to upgrade from mathematica 11.

**Comment by wkotlarski** [comment]
Should we close it?

**Comment by uukhas** [comment]
> Should we close it?

I finally checked this model. It compiles with Mathematica 12

**Comment by pathron** [comment]
That’s great.  Let’s close this.
