### ISSUE TITLE
munuSSM fails to compile

### ISSUE THREAD

**Issue by Expander** [FlexibleSUSY/FlexibleSUSY#82]
In the nightly test the following compilation error occurred:
~~~
models/munuSSM/munuSSM_l_to_lgamma.cpp: In function ‘double flexiblesusy::munuSSM_l_to_lgamma::lepton_total_decay_width(const T1&, const T2&, const flexiblesusy::munuSSM_mass_eigenstates&, const softsusy::QedQcd&)’:
models/munuSSM/munuSSM_l_to_lgamma.cpp:54:43: error: ‘Fe’ was not declared in this scope
    const auto leptonInMass = context.mass<Fe>(indices1);
                                           ^~
models/munuSSM/munuSSM_l_to_lgamma.cpp:54:43: note: suggested alternative: ‘Re’
    const auto leptonInMass = context.mass<Fe>(indices1);
                                           ^~
                                           Re
models/munuSSM/munuSSM_l_to_lgamma.cpp:58:29: error: ‘Fe’ is not a class, namespace, or enumeration
    const double Alpha = Sqr(Fe::electric_charge * unit_charge(context))/(4*Pi);
                             ^~
~~~
The error comes from within the `*_l_to_lgamma.cpp` module.

@wkotlarski would you mind having a look what's going wrong there?

**Comment by wkotlarski** [comment]
Wow. I know what's wrong. Sorry about that.

**Comment by wkotlarski** [comment]
There is one aspect of this which is troubling. I want to get a physical mass of a lepton. For now, I took it from the SLHA input file. For such a weird models this is not possible. If I have 5 "leptons" I, in general, don't know how to map them to SM fields. I can take a pole mass as calculated by FS but then, for example, the muon mass is 0.111 GeV instead of 0.105 GeV. Any ideas?

**Comment by Expander** [comment]
Yes, this is of course a critical point. It is basically the same situation as with the Higgses in the MSSM, where a mixing with the SM-like Higgs occurs and your lightest Higgs may not be "the SM one".

We had this discussion over years and I think there are a few possibilities:

a) We restrict our-selfs to the case where we allow BSM particles which mix with the SM particles to *only be heavier* than the SM one.
b) You infer from the mixing matrix which particle corresponds to which SM-like one. However, this may not be possible if the mixing occurs with equal "weight".
c) You calculate your observable in the full model, including *all* particles. If your observable shall only contain the BSM contribution (like g-2), then you subtract the known SM contribution.

Option c) sounds to be cleanest to me, but I'm sure if it is always applicable. Option a) is probably easiest to implement. Can you find arguments for one of these options?

**Comment by SoundSonic1** [comment]
Subtracting the known SM contribution can be troublesome. For instance, the model might use a different renormalisation scheme. Also, the SM contributions probably contain higher loop corrections than we can calculate for BSM models.

**Comment by Expander** [comment]
That is true, of course, one has to make sure the renormalization scheme matches.

If you can split up the SM contribution into a 1-loop and higher order parts, then I think there should not be a problem, because you can then simply write
~~~
obs(SM) = obs(SM, 1L) + obs(SM, 2L) # known from literature
obs(FS) = obs(full, 1L)   # calculated with FS
obs(BSM, 1L) = obs(full, 1L) - obs(SM, 1L)
~~~

**Comment by wkotlarski** [comment]
My problem is actually different. I don't have a problem with distinguishing between SM and non SM contributions. My question is which pole mass should we use. Case in point - in g-2 routine @iolojz ask for a muon pole mass. The mass that he gets in `munuSSM` using param card distributed with `FlexibleSUSY` is 0.114038 GeV. This shifts the calculated value of `g-2` by 10%. That not optimal ;)

**Comment by Expander** [comment]
I assume the muon pole mass of 0.114038 GeV is the one calculated by FS, right? If so, is this shift maybe caused by a mixing of the extra states with SM-like particles? If so, then I think this shift belongs to the uncertainty of the muon pole mass calculation in FS:

* Input: muon pole mass M
* From this FS calculates the running muon mass m.
* ... [some RG running etc.]
* FS calculates M again from m

In this process, precision could be lost, which may lead to the deviation that you see. An obvious solution would be to use the muon pole mass M that you get from the user in form of an input parameter.

**Comment by wkotlarski** [comment]
Exactly! I'm just reporting that this is not what is done. We should change to use the input value.

**Comment by Expander** [comment]
Definitely!

**Comment by iolojz** [comment]
Erm... Why do the input muon mass not agree with the FS calculated one? I thought the input values were treated as boundary conditions.

**Comment by wkotlarski** [comment]
The pole mass calculated at a fixed order in perturbation theory has residual scale dependence.

**Comment by iolojz** [comment]
Alright, so the input pole mass is used as a boundary condition at the low scale. But we calculate g-2 at the high scale. I guess it makes sense to use the physical input mass then, since it really is just a multiplier of the final result. But you should definitely document it!

**Comment by SoundSonic1** [comment]
Why aren't we calculating g-2 at the low scale? Shouldn't we use an effective field theory approach?

**Comment by Expander** [comment]
g-2 is calculated at the geometric mean of the charged BSM fermions which contribute at 1-loop level. In this way contributions from those charged particles are resummed, which is a good thing as these particles usually give a large contribution.

Btw., it is not only the different scale which leads to the deviation of the input muon pole mass and the one calculated by FS. During the whole calculation (starting from the muon pole mass as input) perturbative series are truncated all over the place. So, there is not only a residual scale dependence of higher order, but also genuine non-logarithmic higher order corrections which come into play. However, formally the relation between the input muon pole mass and the calculated one is formally exact at the 1-loop level, but differs at higher order (both w.r.t. logs and non-log terms).

I absolutely agree with your plans: We should assume that the user-given input value of the muon pole mass is the one which he/she took from experiment and we should take this value.
