### ISSUE TITLE
Use constexpr for constants in ew_input.hpp

### ISSUE THREAD

**Issue by SoundSonic1** [FlexibleSUSY/FlexibleSUSY#86]
Is it possible to declare the numerical constants in the `ew_input.hpp` file as `constexpr` instead of `const`?

**Comment by Expander** [comment]
Good idea! Would you mind providing a patch?

**Comment by SoundSonic1** [comment]
Yes, i can do that. There are a few constants that depend on `sqrt`. They will be left out unless someone creates a `constexpr sqrt_helper`.

**Comment by Expander** [comment]
I think that's ok for the moment.
